/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "BandCombination-v15g0.h"

#include "CA-ParametersNR-v15g0.h"
#include "CA-ParametersNRDC-v15g0.h"
#include "MRDC-Parameters-v15g0.h"
asn_TYPE_member_t asn_MBR_BandCombination_v15g0_1[] = {
	{ ATF_POINTER, 3, offsetof(struct BandCombination_v15g0, ca_ParametersNR_v15g0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CA_ParametersNR_v15g0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-ParametersNR-v15g0"
		},
	{ ATF_POINTER, 2, offsetof(struct BandCombination_v15g0, ca_ParametersNRDC_v15g0),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CA_ParametersNRDC_v15g0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-ParametersNRDC-v15g0"
		},
	{ ATF_POINTER, 1, offsetof(struct BandCombination_v15g0, mrdc_Parameters_v15g0),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MRDC_Parameters_v15g0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mrdc-Parameters-v15g0"
		},
};
static const int asn_MAP_BandCombination_v15g0_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_BandCombination_v15g0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BandCombination_v15g0_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ca-ParametersNR-v15g0 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ca-ParametersNRDC-v15g0 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* mrdc-Parameters-v15g0 */
};
asn_SEQUENCE_specifics_t asn_SPC_BandCombination_v15g0_specs_1 = {
	sizeof(struct BandCombination_v15g0),
	offsetof(struct BandCombination_v15g0, _asn_ctx),
	asn_MAP_BandCombination_v15g0_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_BandCombination_v15g0_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BandCombination_v15g0 = {
	"BandCombination-v15g0",
	"BandCombination-v15g0",
	&asn_OP_SEQUENCE,
	asn_DEF_BandCombination_v15g0_tags_1,
	sizeof(asn_DEF_BandCombination_v15g0_tags_1)
		/sizeof(asn_DEF_BandCombination_v15g0_tags_1[0]), /* 1 */
	asn_DEF_BandCombination_v15g0_tags_1,	/* Same as above */
	sizeof(asn_DEF_BandCombination_v15g0_tags_1)
		/sizeof(asn_DEF_BandCombination_v15g0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BandCombination_v15g0_1,
	3,	/* Elements count */
	&asn_SPC_BandCombination_v15g0_specs_1	/* Additional specs */
};

