/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CA_ParametersNRDC_H_
#define	_CA_ParametersNRDC_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FeatureSetCombinationId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CA_ParametersNR;
struct CA_ParametersNR_v1540;
struct CA_ParametersNR_v1550;
struct CA_ParametersNR_v1560;

/* CA-ParametersNRDC */
typedef struct CA_ParametersNRDC {
	struct CA_ParametersNR	*ca_ParametersNR_ForDC	/* OPTIONAL */;
	struct CA_ParametersNR_v1540	*ca_ParametersNR_ForDC_v1540	/* OPTIONAL */;
	struct CA_ParametersNR_v1550	*ca_ParametersNR_ForDC_v1550	/* OPTIONAL */;
	struct CA_ParametersNR_v1560	*ca_ParametersNR_ForDC_v1560	/* OPTIONAL */;
	FeatureSetCombinationId_t	*featureSetCombinationDC	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNRDC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNRDC;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNRDC_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNRDC_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CA_ParametersNRDC_H_ */
#include <asn_internal.h>
