/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "CG-Config-v1590-IEs.h"

static int
memb_scellFrequenciesSN_NR_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 31)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_scellFrequenciesSN_EUTRA_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 31)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_scellFrequenciesSN_NR_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..31)) */};
static asn_per_constraints_t asn_PER_type_scellFrequenciesSN_NR_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  31 }	/* (SIZE(1..31)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_scellFrequenciesSN_EUTRA_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..31)) */};
static asn_per_constraints_t asn_PER_type_scellFrequenciesSN_EUTRA_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  31 }	/* (SIZE(1..31)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_scellFrequenciesSN_NR_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..31)) */};
static asn_per_constraints_t asn_PER_memb_scellFrequenciesSN_NR_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  31 }	/* (SIZE(1..31)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_scellFrequenciesSN_EUTRA_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..31)) */};
static asn_per_constraints_t asn_PER_memb_scellFrequenciesSN_EUTRA_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  31 }	/* (SIZE(1..31)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_scellFrequenciesSN_NR_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ARFCN_ValueNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_scellFrequenciesSN_NR_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_scellFrequenciesSN_NR_specs_2 = {
	sizeof(struct CG_Config_v1590_IEs__scellFrequenciesSN_NR),
	offsetof(struct CG_Config_v1590_IEs__scellFrequenciesSN_NR, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scellFrequenciesSN_NR_2 = {
	"scellFrequenciesSN-NR",
	"scellFrequenciesSN-NR",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_scellFrequenciesSN_NR_tags_2,
	sizeof(asn_DEF_scellFrequenciesSN_NR_tags_2)
		/sizeof(asn_DEF_scellFrequenciesSN_NR_tags_2[0]) - 1, /* 1 */
	asn_DEF_scellFrequenciesSN_NR_tags_2,	/* Same as above */
	sizeof(asn_DEF_scellFrequenciesSN_NR_tags_2)
		/sizeof(asn_DEF_scellFrequenciesSN_NR_tags_2[0]), /* 2 */
	{ &asn_OER_type_scellFrequenciesSN_NR_constr_2, &asn_PER_type_scellFrequenciesSN_NR_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_scellFrequenciesSN_NR_2,
	1,	/* Single element */
	&asn_SPC_scellFrequenciesSN_NR_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_scellFrequenciesSN_EUTRA_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ARFCN_ValueEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_scellFrequenciesSN_EUTRA_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_scellFrequenciesSN_EUTRA_specs_4 = {
	sizeof(struct CG_Config_v1590_IEs__scellFrequenciesSN_EUTRA),
	offsetof(struct CG_Config_v1590_IEs__scellFrequenciesSN_EUTRA, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scellFrequenciesSN_EUTRA_4 = {
	"scellFrequenciesSN-EUTRA",
	"scellFrequenciesSN-EUTRA",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_scellFrequenciesSN_EUTRA_tags_4,
	sizeof(asn_DEF_scellFrequenciesSN_EUTRA_tags_4)
		/sizeof(asn_DEF_scellFrequenciesSN_EUTRA_tags_4[0]) - 1, /* 1 */
	asn_DEF_scellFrequenciesSN_EUTRA_tags_4,	/* Same as above */
	sizeof(asn_DEF_scellFrequenciesSN_EUTRA_tags_4)
		/sizeof(asn_DEF_scellFrequenciesSN_EUTRA_tags_4[0]), /* 2 */
	{ &asn_OER_type_scellFrequenciesSN_EUTRA_constr_4, &asn_PER_type_scellFrequenciesSN_EUTRA_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_scellFrequenciesSN_EUTRA_4,
	1,	/* Single element */
	&asn_SPC_scellFrequenciesSN_EUTRA_specs_4	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtension_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_6 = {
	sizeof(struct CG_Config_v1590_IEs__nonCriticalExtension),
	offsetof(struct CG_Config_v1590_IEs__nonCriticalExtension, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_6 = {
	"nonCriticalExtension",
	"nonCriticalExtension",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtension_tags_6,
	sizeof(asn_DEF_nonCriticalExtension_tags_6)
		/sizeof(asn_DEF_nonCriticalExtension_tags_6[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtension_tags_6,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtension_tags_6)
		/sizeof(asn_DEF_nonCriticalExtension_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CG_Config_v1590_IEs_1[] = {
	{ ATF_POINTER, 3, offsetof(struct CG_Config_v1590_IEs, scellFrequenciesSN_NR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_scellFrequenciesSN_NR_2,
		0,
		{ &asn_OER_memb_scellFrequenciesSN_NR_constr_2, &asn_PER_memb_scellFrequenciesSN_NR_constr_2,  memb_scellFrequenciesSN_NR_constraint_1 },
		0, 0, /* No default value */
		"scellFrequenciesSN-NR"
		},
	{ ATF_POINTER, 2, offsetof(struct CG_Config_v1590_IEs, scellFrequenciesSN_EUTRA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_scellFrequenciesSN_EUTRA_4,
		0,
		{ &asn_OER_memb_scellFrequenciesSN_EUTRA_constr_4, &asn_PER_memb_scellFrequenciesSN_EUTRA_constr_4,  memb_scellFrequenciesSN_EUTRA_constraint_1 },
		0, 0, /* No default value */
		"scellFrequenciesSN-EUTRA"
		},
	{ ATF_POINTER, 1, offsetof(struct CG_Config_v1590_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonCriticalExtension_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtension"
		},
};
static const int asn_MAP_CG_Config_v1590_IEs_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_CG_Config_v1590_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CG_Config_v1590_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scellFrequenciesSN-NR */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* scellFrequenciesSN-EUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_CG_Config_v1590_IEs_specs_1 = {
	sizeof(struct CG_Config_v1590_IEs),
	offsetof(struct CG_Config_v1590_IEs, _asn_ctx),
	asn_MAP_CG_Config_v1590_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_CG_Config_v1590_IEs_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CG_Config_v1590_IEs = {
	"CG-Config-v1590-IEs",
	"CG-Config-v1590-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_CG_Config_v1590_IEs_tags_1,
	sizeof(asn_DEF_CG_Config_v1590_IEs_tags_1)
		/sizeof(asn_DEF_CG_Config_v1590_IEs_tags_1[0]), /* 1 */
	asn_DEF_CG_Config_v1590_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_CG_Config_v1590_IEs_tags_1)
		/sizeof(asn_DEF_CG_Config_v1590_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CG_Config_v1590_IEs_1,
	3,	/* Elements count */
	&asn_SPC_CG_Config_v1590_IEs_specs_1	/* Additional specs */
};

