/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "CG-ConfigInfo-v1570-IEs.h"

#include "SFTD-FrequencyList-NR.h"
#include "SFTD-FrequencyList-EUTRA.h"
#include "CG-ConfigInfo-v1590-IEs.h"
asn_TYPE_member_t asn_MBR_CG_ConfigInfo_v1570_IEs_1[] = {
	{ ATF_POINTER, 3, offsetof(struct CG_ConfigInfo_v1570_IEs, sftdFrequencyList_NR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SFTD_FrequencyList_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sftdFrequencyList-NR"
		},
	{ ATF_POINTER, 2, offsetof(struct CG_ConfigInfo_v1570_IEs, sftdFrequencyList_EUTRA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SFTD_FrequencyList_EUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sftdFrequencyList-EUTRA"
		},
	{ ATF_POINTER, 1, offsetof(struct CG_ConfigInfo_v1570_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CG_ConfigInfo_v1590_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtension"
		},
};
static const int asn_MAP_CG_ConfigInfo_v1570_IEs_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CG_ConfigInfo_v1570_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sftdFrequencyList-NR */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sftdFrequencyList-EUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_CG_ConfigInfo_v1570_IEs_specs_1 = {
	sizeof(struct CG_ConfigInfo_v1570_IEs),
	offsetof(struct CG_ConfigInfo_v1570_IEs, _asn_ctx),
	asn_MAP_CG_ConfigInfo_v1570_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_CG_ConfigInfo_v1570_IEs_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CG_ConfigInfo_v1570_IEs = {
	"CG-ConfigInfo-v1570-IEs",
	"CG-ConfigInfo-v1570-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1,
	sizeof(asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1)
		/sizeof(asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1[0]), /* 1 */
	asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1)
		/sizeof(asn_DEF_CG_ConfigInfo_v1570_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CG_ConfigInfo_v1570_IEs_1,
	3,	/* Elements count */
	&asn_SPC_CG_ConfigInfo_v1570_IEs_specs_1	/* Additional specs */
};

