/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_MAC_CellGroupConfig_H_
#define	_MAC_CellGroupConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease;
struct SchedulingRequestConfig;
struct BSR_Config;
struct TAG_Config;

/* MAC-CellGroupConfig */
typedef struct MAC_CellGroupConfig {
	struct SetupRelease	*drx_Config	/* OPTIONAL */;
	struct SchedulingRequestConfig	*schedulingRequestConfig	/* OPTIONAL */;
	struct BSR_Config	*bsr_Config	/* OPTIONAL */;
	struct TAG_Config	*tag_Config	/* OPTIONAL */;
	struct SetupRelease	*phr_Config	/* OPTIONAL */;
	BOOLEAN_t	 skipUplinkTxDynamic;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	BOOLEAN_t	*csi_Mask	/* OPTIONAL */;
	struct SetupRelease	*dataInactivityTimer	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAC_CellGroupConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAC_CellGroupConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_MAC_CellGroupConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_MAC_CellGroupConfig_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _MAC_CellGroupConfig_H_ */
#include <asn_internal.h>
