/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "MeasAndMobParametersFRX-Diff.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ss_SINR_Meas_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ss_SINR_Meas_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_csi_RSRP_AndRSRQ_MeasWithSSB_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_csi_RSRP_AndRSRQ_MeasWithSSB_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_csi_RSRP_AndRSRQ_MeasWithoutSSB_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_csi_RSRP_AndRSRQ_MeasWithoutSSB_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_csi_SINR_Meas_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_csi_SINR_Meas_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_csi_RS_RLM_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_csi_RS_RLM_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_handoverInterF_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_handoverInterF_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_handoverLTE_EPC_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_handoverLTE_EPC_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_handoverLTE_5GC_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_handoverLTE_5GC_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_maxNumberResource_CSI_RS_RLM_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_maxNumberResource_CSI_RS_RLM_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_simultaneousRxDataSSB_DiffNumerology_constr_24 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_simultaneousRxDataSSB_DiffNumerology_constr_24 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ss_SINR_Meas_value2enum_2[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ss_SINR_Meas_enum2value_2[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ss_SINR_Meas_specs_2 = {
	asn_MAP_ss_SINR_Meas_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ss_SINR_Meas_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ss_SINR_Meas_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ss_SINR_Meas_2 = {
	"ss-SINR-Meas",
	"ss-SINR-Meas",
	&asn_OP_NativeEnumerated,
	asn_DEF_ss_SINR_Meas_tags_2,
	sizeof(asn_DEF_ss_SINR_Meas_tags_2)
		/sizeof(asn_DEF_ss_SINR_Meas_tags_2[0]) - 1, /* 1 */
	asn_DEF_ss_SINR_Meas_tags_2,	/* Same as above */
	sizeof(asn_DEF_ss_SINR_Meas_tags_2)
		/sizeof(asn_DEF_ss_SINR_Meas_tags_2[0]), /* 2 */
	{ &asn_OER_type_ss_SINR_Meas_constr_2, &asn_PER_type_ss_SINR_Meas_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ss_SINR_Meas_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_csi_RSRP_AndRSRQ_MeasWithSSB_value2enum_4[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_csi_RSRP_AndRSRQ_MeasWithSSB_enum2value_4[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_csi_RSRP_AndRSRQ_MeasWithSSB_specs_4 = {
	asn_MAP_csi_RSRP_AndRSRQ_MeasWithSSB_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_csi_RSRP_AndRSRQ_MeasWithSSB_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_4 = {
	"csi-RSRP-AndRSRQ-MeasWithSSB",
	"csi-RSRP-AndRSRQ-MeasWithSSB",
	&asn_OP_NativeEnumerated,
	asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4,
	sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4)
		/sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4[0]) - 1, /* 1 */
	asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4,	/* Same as above */
	sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4)
		/sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_tags_4[0]), /* 2 */
	{ &asn_OER_type_csi_RSRP_AndRSRQ_MeasWithSSB_constr_4, &asn_PER_type_csi_RSRP_AndRSRQ_MeasWithSSB_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csi_RSRP_AndRSRQ_MeasWithSSB_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_csi_RSRP_AndRSRQ_MeasWithoutSSB_value2enum_6[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_csi_RSRP_AndRSRQ_MeasWithoutSSB_enum2value_6[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_csi_RSRP_AndRSRQ_MeasWithoutSSB_specs_6 = {
	asn_MAP_csi_RSRP_AndRSRQ_MeasWithoutSSB_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_csi_RSRP_AndRSRQ_MeasWithoutSSB_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_6 = {
	"csi-RSRP-AndRSRQ-MeasWithoutSSB",
	"csi-RSRP-AndRSRQ-MeasWithoutSSB",
	&asn_OP_NativeEnumerated,
	asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6,
	sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6)
		/sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6[0]) - 1, /* 1 */
	asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6,	/* Same as above */
	sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6)
		/sizeof(asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_tags_6[0]), /* 2 */
	{ &asn_OER_type_csi_RSRP_AndRSRQ_MeasWithoutSSB_constr_6, &asn_PER_type_csi_RSRP_AndRSRQ_MeasWithoutSSB_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csi_RSRP_AndRSRQ_MeasWithoutSSB_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_csi_SINR_Meas_value2enum_8[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_csi_SINR_Meas_enum2value_8[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_csi_SINR_Meas_specs_8 = {
	asn_MAP_csi_SINR_Meas_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_csi_SINR_Meas_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_csi_SINR_Meas_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_SINR_Meas_8 = {
	"csi-SINR-Meas",
	"csi-SINR-Meas",
	&asn_OP_NativeEnumerated,
	asn_DEF_csi_SINR_Meas_tags_8,
	sizeof(asn_DEF_csi_SINR_Meas_tags_8)
		/sizeof(asn_DEF_csi_SINR_Meas_tags_8[0]) - 1, /* 1 */
	asn_DEF_csi_SINR_Meas_tags_8,	/* Same as above */
	sizeof(asn_DEF_csi_SINR_Meas_tags_8)
		/sizeof(asn_DEF_csi_SINR_Meas_tags_8[0]), /* 2 */
	{ &asn_OER_type_csi_SINR_Meas_constr_8, &asn_PER_type_csi_SINR_Meas_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csi_SINR_Meas_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_csi_RS_RLM_value2enum_10[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_csi_RS_RLM_enum2value_10[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_csi_RS_RLM_specs_10 = {
	asn_MAP_csi_RS_RLM_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_csi_RS_RLM_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_csi_RS_RLM_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_RS_RLM_10 = {
	"csi-RS-RLM",
	"csi-RS-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_csi_RS_RLM_tags_10,
	sizeof(asn_DEF_csi_RS_RLM_tags_10)
		/sizeof(asn_DEF_csi_RS_RLM_tags_10[0]) - 1, /* 1 */
	asn_DEF_csi_RS_RLM_tags_10,	/* Same as above */
	sizeof(asn_DEF_csi_RS_RLM_tags_10)
		/sizeof(asn_DEF_csi_RS_RLM_tags_10[0]), /* 2 */
	{ &asn_OER_type_csi_RS_RLM_constr_10, &asn_PER_type_csi_RS_RLM_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csi_RS_RLM_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_handoverInterF_value2enum_13[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_handoverInterF_enum2value_13[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_handoverInterF_specs_13 = {
	asn_MAP_handoverInterF_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverInterF_enum2value_13,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_handoverInterF_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverInterF_13 = {
	"handoverInterF",
	"handoverInterF",
	&asn_OP_NativeEnumerated,
	asn_DEF_handoverInterF_tags_13,
	sizeof(asn_DEF_handoverInterF_tags_13)
		/sizeof(asn_DEF_handoverInterF_tags_13[0]) - 1, /* 1 */
	asn_DEF_handoverInterF_tags_13,	/* Same as above */
	sizeof(asn_DEF_handoverInterF_tags_13)
		/sizeof(asn_DEF_handoverInterF_tags_13[0]), /* 2 */
	{ &asn_OER_type_handoverInterF_constr_13, &asn_PER_type_handoverInterF_constr_13, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverInterF_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_handoverLTE_EPC_value2enum_15[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_handoverLTE_EPC_enum2value_15[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_handoverLTE_EPC_specs_15 = {
	asn_MAP_handoverLTE_EPC_value2enum_15,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverLTE_EPC_enum2value_15,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_handoverLTE_EPC_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverLTE_EPC_15 = {
	"handoverLTE-EPC",
	"handoverLTE-EPC",
	&asn_OP_NativeEnumerated,
	asn_DEF_handoverLTE_EPC_tags_15,
	sizeof(asn_DEF_handoverLTE_EPC_tags_15)
		/sizeof(asn_DEF_handoverLTE_EPC_tags_15[0]) - 1, /* 1 */
	asn_DEF_handoverLTE_EPC_tags_15,	/* Same as above */
	sizeof(asn_DEF_handoverLTE_EPC_tags_15)
		/sizeof(asn_DEF_handoverLTE_EPC_tags_15[0]), /* 2 */
	{ &asn_OER_type_handoverLTE_EPC_constr_15, &asn_PER_type_handoverLTE_EPC_constr_15, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverLTE_EPC_specs_15	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_handoverLTE_5GC_value2enum_17[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_handoverLTE_5GC_enum2value_17[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_handoverLTE_5GC_specs_17 = {
	asn_MAP_handoverLTE_5GC_value2enum_17,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverLTE_5GC_enum2value_17,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_handoverLTE_5GC_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverLTE_5GC_17 = {
	"handoverLTE-5GC",
	"handoverLTE-5GC",
	&asn_OP_NativeEnumerated,
	asn_DEF_handoverLTE_5GC_tags_17,
	sizeof(asn_DEF_handoverLTE_5GC_tags_17)
		/sizeof(asn_DEF_handoverLTE_5GC_tags_17[0]) - 1, /* 1 */
	asn_DEF_handoverLTE_5GC_tags_17,	/* Same as above */
	sizeof(asn_DEF_handoverLTE_5GC_tags_17)
		/sizeof(asn_DEF_handoverLTE_5GC_tags_17[0]), /* 2 */
	{ &asn_OER_type_handoverLTE_5GC_constr_17, &asn_PER_type_handoverLTE_5GC_constr_17, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverLTE_5GC_specs_17	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumberResource_CSI_RS_RLM_value2enum_19[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n4" },
	{ 2,	2,	"n6" },
	{ 3,	2,	"n8" }
};
static const unsigned int asn_MAP_maxNumberResource_CSI_RS_RLM_enum2value_19[] = {
	0,	/* n2(0) */
	1,	/* n4(1) */
	2,	/* n6(2) */
	3	/* n8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumberResource_CSI_RS_RLM_specs_19 = {
	asn_MAP_maxNumberResource_CSI_RS_RLM_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumberResource_CSI_RS_RLM_enum2value_19,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumberResource_CSI_RS_RLM_19 = {
	"maxNumberResource-CSI-RS-RLM",
	"maxNumberResource-CSI-RS-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19,
	sizeof(asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19)
		/sizeof(asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19[0]) - 1, /* 1 */
	asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19,	/* Same as above */
	sizeof(asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19)
		/sizeof(asn_DEF_maxNumberResource_CSI_RS_RLM_tags_19[0]), /* 2 */
	{ &asn_OER_type_maxNumberResource_CSI_RS_RLM_constr_19, &asn_PER_type_maxNumberResource_CSI_RS_RLM_constr_19, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumberResource_CSI_RS_RLM_specs_19	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_simultaneousRxDataSSB_DiffNumerology_value2enum_24[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_simultaneousRxDataSSB_DiffNumerology_enum2value_24[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_simultaneousRxDataSSB_DiffNumerology_specs_24 = {
	asn_MAP_simultaneousRxDataSSB_DiffNumerology_value2enum_24,	/* "tag" => N; sorted by tag */
	asn_MAP_simultaneousRxDataSSB_DiffNumerology_enum2value_24,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_simultaneousRxDataSSB_DiffNumerology_24 = {
	"simultaneousRxDataSSB-DiffNumerology",
	"simultaneousRxDataSSB-DiffNumerology",
	&asn_OP_NativeEnumerated,
	asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24,
	sizeof(asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24)
		/sizeof(asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24[0]) - 1, /* 1 */
	asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24,	/* Same as above */
	sizeof(asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24)
		/sizeof(asn_DEF_simultaneousRxDataSSB_DiffNumerology_tags_24[0]), /* 2 */
	{ &asn_OER_type_simultaneousRxDataSSB_DiffNumerology_constr_24, &asn_PER_type_simultaneousRxDataSSB_DiffNumerology_constr_24, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_simultaneousRxDataSSB_DiffNumerology_specs_24	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasAndMobParametersFRX_Diff_1[] = {
	{ ATF_POINTER, 10, offsetof(struct MeasAndMobParametersFRX_Diff, ss_SINR_Meas),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ss_SINR_Meas_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ss-SINR-Meas"
		},
	{ ATF_POINTER, 9, offsetof(struct MeasAndMobParametersFRX_Diff, csi_RSRP_AndRSRQ_MeasWithSSB),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RSRP-AndRSRQ-MeasWithSSB"
		},
	{ ATF_POINTER, 8, offsetof(struct MeasAndMobParametersFRX_Diff, csi_RSRP_AndRSRQ_MeasWithoutSSB),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RSRP-AndRSRQ-MeasWithoutSSB"
		},
	{ ATF_POINTER, 7, offsetof(struct MeasAndMobParametersFRX_Diff, csi_SINR_Meas),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csi_SINR_Meas_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-SINR-Meas"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasAndMobParametersFRX_Diff, csi_RS_RLM),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csi_RS_RLM_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-RLM"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasAndMobParametersFRX_Diff, handoverInterF),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverInterF_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverInterF"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasAndMobParametersFRX_Diff, handoverLTE_EPC),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverLTE_EPC_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverLTE-EPC"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasAndMobParametersFRX_Diff, handoverLTE_5GC),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverLTE_5GC_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverLTE-5GC"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasAndMobParametersFRX_Diff, maxNumberResource_CSI_RS_RLM),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumberResource_CSI_RS_RLM_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberResource-CSI-RS-RLM"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasAndMobParametersFRX_Diff, simultaneousRxDataSSB_DiffNumerology),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_simultaneousRxDataSSB_DiffNumerology_24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simultaneousRxDataSSB-DiffNumerology"
		},
};
static const int asn_MAP_MeasAndMobParametersFRX_Diff_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_MeasAndMobParametersFRX_Diff_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasAndMobParametersFRX_Diff_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ss-SINR-Meas */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* csi-RSRP-AndRSRQ-MeasWithSSB */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* csi-RSRP-AndRSRQ-MeasWithoutSSB */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* csi-SINR-Meas */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* csi-RS-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* handoverInterF */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* handoverLTE-EPC */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* handoverLTE-5GC */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* maxNumberResource-CSI-RS-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* simultaneousRxDataSSB-DiffNumerology */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasAndMobParametersFRX_Diff_specs_1 = {
	sizeof(struct MeasAndMobParametersFRX_Diff),
	offsetof(struct MeasAndMobParametersFRX_Diff, _asn_ctx),
	asn_MAP_MeasAndMobParametersFRX_Diff_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_MeasAndMobParametersFRX_Diff_oms_1,	/* Optional members */
	5, 5,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasAndMobParametersFRX_Diff = {
	"MeasAndMobParametersFRX-Diff",
	"MeasAndMobParametersFRX-Diff",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasAndMobParametersFRX_Diff_tags_1,
	sizeof(asn_DEF_MeasAndMobParametersFRX_Diff_tags_1)
		/sizeof(asn_DEF_MeasAndMobParametersFRX_Diff_tags_1[0]), /* 1 */
	asn_DEF_MeasAndMobParametersFRX_Diff_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasAndMobParametersFRX_Diff_tags_1)
		/sizeof(asn_DEF_MeasAndMobParametersFRX_Diff_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasAndMobParametersFRX_Diff_1,
	10,	/* Elements count */
	&asn_SPC_MeasAndMobParametersFRX_Diff_specs_1	/* Additional specs */
};

