/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_DL_SCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_PCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_CCCH1_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UECapabilityEnquiry_v1560_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_CellGroupConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasResultSCG_Failure;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_CapabilityRequestFilterNR;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_MRDC_Capability;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_MRDC_Capability_v15g0;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_NR_Capability;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_NR_Capability_v15c0;
extern struct asn_TYPE_descriptor_s asn_DEF_VarPendingRNA_Update;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasReportList;
extern struct asn_TYPE_descriptor_s asn_DEF_VarResumeMAC_Input;
extern struct asn_TYPE_descriptor_s asn_DEF_VarShortMAC_Input;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverPreparationInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_CG_Config;
extern struct asn_TYPE_descriptor_s asn_DEF_CG_ConfigInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementTimingConfiguration;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioPagingInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioAccessCapabilityInformation;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module NR-RRC-Definitions in 38331-15.asn */
	&asn_DEF_BCCH_BCH_Message,	
	&asn_DEF_BCCH_DL_SCH_Message,	
	&asn_DEF_DL_CCCH_Message,	
	&asn_DEF_DL_DCCH_Message,	
	&asn_DEF_PCCH_Message,	
	&asn_DEF_UL_CCCH_Message,	
	&asn_DEF_UL_CCCH1_Message,	
	&asn_DEF_UL_DCCH_Message,	
	&asn_DEF_UECapabilityEnquiry_v1560_IEs,	
	&asn_DEF_CellGroupConfig,	
	&asn_DEF_MeasResultSCG_Failure,	
	&asn_DEF_UE_CapabilityRequestFilterNR,	
	&asn_DEF_UE_MRDC_Capability,	
	&asn_DEF_UE_MRDC_Capability_v15g0,	
	&asn_DEF_UE_NR_Capability,	
	&asn_DEF_UE_NR_Capability_v15c0,	
	/* From module NR-UE-Variables in 38331-15.asn */
	&asn_DEF_VarPendingRNA_Update,	
	&asn_DEF_VarMeasConfig,	
	&asn_DEF_VarMeasReportList,	
	&asn_DEF_VarResumeMAC_Input,	
	&asn_DEF_VarShortMAC_Input,	
	/* From module NR-InterNodeDefinitions in 38331-15.asn */
	&asn_DEF_HandoverCommand,	
	&asn_DEF_HandoverPreparationInformation,	
	&asn_DEF_CG_Config,	
	&asn_DEF_CG_ConfigInfo,	
	&asn_DEF_MeasurementTimingConfiguration,	
	&asn_DEF_UERadioPagingInformation,	
	&asn_DEF_UERadioAccessCapabilityInformation,	
	0
};

