/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_RF_ParametersMRDC_H_
#define	_RF_ParametersMRDC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RF_ParametersMRDC__srs_SwitchingTimeRequested {
	RF_ParametersMRDC__srs_SwitchingTimeRequested_true	= 0
} e_RF_ParametersMRDC__srs_SwitchingTimeRequested;

/* Forward declarations */
struct BandCombinationList;
struct FreqBandList;
struct BandCombinationList_v1540;
struct BandCombinationList_v1550;
struct BandCombinationList_v1560;
struct BandCombinationList_v1570;
struct BandCombinationList_v1580;
struct BandCombinationList_v1590;

/* RF-ParametersMRDC */
typedef struct RF_ParametersMRDC {
	struct BandCombinationList	*supportedBandCombinationList	/* OPTIONAL */;
	struct FreqBandList	*appliedFreqBandListFilter	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*srs_SwitchingTimeRequested	/* OPTIONAL */;
	struct BandCombinationList_v1540	*supportedBandCombinationList_v1540	/* OPTIONAL */;
	struct BandCombinationList_v1550	*supportedBandCombinationList_v1550	/* OPTIONAL */;
	struct BandCombinationList_v1560	*supportedBandCombinationList_v1560	/* OPTIONAL */;
	struct BandCombinationList	*supportedBandCombinationListNEDC_Only	/* OPTIONAL */;
	struct BandCombinationList_v1570	*supportedBandCombinationList_v1570	/* OPTIONAL */;
	struct BandCombinationList_v1580	*supportedBandCombinationList_v1580	/* OPTIONAL */;
	struct BandCombinationList_v1590	*supportedBandCombinationList_v1590	/* OPTIONAL */;
	struct RF_ParametersMRDC__supportedBandCombinationListNEDC_Only_v15a0 {
		struct BandCombinationList_v1540	*supportedBandCombinationList_v1540	/* OPTIONAL */;
		struct BandCombinationList_v1560	*supportedBandCombinationList_v1560	/* OPTIONAL */;
		struct BandCombinationList_v1570	*supportedBandCombinationList_v1570	/* OPTIONAL */;
		struct BandCombinationList_v1580	*supportedBandCombinationList_v1580	/* OPTIONAL */;
		struct BandCombinationList_v1590	*supportedBandCombinationList_v1590	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *supportedBandCombinationListNEDC_Only_v15a0;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_ParametersMRDC_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_srs_SwitchingTimeRequested_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RF_ParametersMRDC;
extern asn_SEQUENCE_specifics_t asn_SPC_RF_ParametersMRDC_specs_1;
extern asn_TYPE_member_t asn_MBR_RF_ParametersMRDC_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _RF_ParametersMRDC_H_ */
#include <asn_internal.h>
