/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SetupRelease_H_
#define	_SetupRelease_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include "DataInactivityTimer.h"
#include "MeasGapSharingScheme.h"
#include "RNTI-Value.h"
#include "PDCCH-BlindDetection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SetupRelease_1084P0_PR {
	SetupRelease_1084P0_PR_NOTHING,	/* No components present */
	SetupRelease_1084P0_PR_release,
	SetupRelease_1084P0_PR_setup
} SetupRelease_1084P0_PR;
typedef enum SetupRelease_1084P1_PR {
	SetupRelease_1084P1_PR_NOTHING,	/* No components present */
	SetupRelease_1084P1_PR_release,
	SetupRelease_1084P1_PR_setup
} SetupRelease_1084P1_PR;
typedef enum SetupRelease_1084P2_PR {
	SetupRelease_1084P2_PR_NOTHING,	/* No components present */
	SetupRelease_1084P2_PR_release,
	SetupRelease_1084P2_PR_setup
} SetupRelease_1084P2_PR;
typedef enum SetupRelease_1084P3_PR {
	SetupRelease_1084P3_PR_NOTHING,	/* No components present */
	SetupRelease_1084P3_PR_release,
	SetupRelease_1084P3_PR_setup
} SetupRelease_1084P3_PR;
typedef enum SetupRelease_1084P4_PR {
	SetupRelease_1084P4_PR_NOTHING,	/* No components present */
	SetupRelease_1084P4_PR_release,
	SetupRelease_1084P4_PR_setup
} SetupRelease_1084P4_PR;
typedef enum SetupRelease_1084P5_PR {
	SetupRelease_1084P5_PR_NOTHING,	/* No components present */
	SetupRelease_1084P5_PR_release,
	SetupRelease_1084P5_PR_setup
} SetupRelease_1084P5_PR;
typedef enum SetupRelease_1084P6_PR {
	SetupRelease_1084P6_PR_NOTHING,	/* No components present */
	SetupRelease_1084P6_PR_release,
	SetupRelease_1084P6_PR_setup
} SetupRelease_1084P6_PR;
typedef enum SetupRelease_1084P7_PR {
	SetupRelease_1084P7_PR_NOTHING,	/* No components present */
	SetupRelease_1084P7_PR_release,
	SetupRelease_1084P7_PR_setup
} SetupRelease_1084P7_PR;
typedef enum SetupRelease_1084P8_PR {
	SetupRelease_1084P8_PR_NOTHING,	/* No components present */
	SetupRelease_1084P8_PR_release,
	SetupRelease_1084P8_PR_setup
} SetupRelease_1084P8_PR;
typedef enum SetupRelease_1084P9_PR {
	SetupRelease_1084P9_PR_NOTHING,	/* No components present */
	SetupRelease_1084P9_PR_release,
	SetupRelease_1084P9_PR_setup
} SetupRelease_1084P9_PR;
typedef enum SetupRelease_1084P10_PR {
	SetupRelease_1084P10_PR_NOTHING,	/* No components present */
	SetupRelease_1084P10_PR_release,
	SetupRelease_1084P10_PR_setup
} SetupRelease_1084P10_PR;
typedef enum SetupRelease_1084P11_PR {
	SetupRelease_1084P11_PR_NOTHING,	/* No components present */
	SetupRelease_1084P11_PR_release,
	SetupRelease_1084P11_PR_setup
} SetupRelease_1084P11_PR;
typedef enum SetupRelease_1084P12_PR {
	SetupRelease_1084P12_PR_NOTHING,	/* No components present */
	SetupRelease_1084P12_PR_release,
	SetupRelease_1084P12_PR_setup
} SetupRelease_1084P12_PR;
typedef enum SetupRelease_1084P13_PR {
	SetupRelease_1084P13_PR_NOTHING,	/* No components present */
	SetupRelease_1084P13_PR_release,
	SetupRelease_1084P13_PR_setup
} SetupRelease_1084P13_PR;
typedef enum SetupRelease_1084P14_PR {
	SetupRelease_1084P14_PR_NOTHING,	/* No components present */
	SetupRelease_1084P14_PR_release,
	SetupRelease_1084P14_PR_setup
} SetupRelease_1084P14_PR;
typedef enum SetupRelease_1084P15_PR {
	SetupRelease_1084P15_PR_NOTHING,	/* No components present */
	SetupRelease_1084P15_PR_release,
	SetupRelease_1084P15_PR_setup
} SetupRelease_1084P15_PR;
typedef enum SetupRelease_1084P16_PR {
	SetupRelease_1084P16_PR_NOTHING,	/* No components present */
	SetupRelease_1084P16_PR_release,
	SetupRelease_1084P16_PR_setup
} SetupRelease_1084P16_PR;
typedef enum SetupRelease_1084P17_PR {
	SetupRelease_1084P17_PR_NOTHING,	/* No components present */
	SetupRelease_1084P17_PR_release,
	SetupRelease_1084P17_PR_setup
} SetupRelease_1084P17_PR;
typedef enum SetupRelease_1084P18_PR {
	SetupRelease_1084P18_PR_NOTHING,	/* No components present */
	SetupRelease_1084P18_PR_release,
	SetupRelease_1084P18_PR_setup
} SetupRelease_1084P18_PR;
typedef enum SetupRelease_1084P19_PR {
	SetupRelease_1084P19_PR_NOTHING,	/* No components present */
	SetupRelease_1084P19_PR_release,
	SetupRelease_1084P19_PR_setup
} SetupRelease_1084P19_PR;
typedef enum SetupRelease_1084P20_PR {
	SetupRelease_1084P20_PR_NOTHING,	/* No components present */
	SetupRelease_1084P20_PR_release,
	SetupRelease_1084P20_PR_setup
} SetupRelease_1084P20_PR;
typedef enum SetupRelease_1084P21_PR {
	SetupRelease_1084P21_PR_NOTHING,	/* No components present */
	SetupRelease_1084P21_PR_release,
	SetupRelease_1084P21_PR_setup
} SetupRelease_1084P21_PR;
typedef enum SetupRelease_1084P22_PR {
	SetupRelease_1084P22_PR_NOTHING,	/* No components present */
	SetupRelease_1084P22_PR_release,
	SetupRelease_1084P22_PR_setup
} SetupRelease_1084P22_PR;
typedef enum SetupRelease_1084P23_PR {
	SetupRelease_1084P23_PR_NOTHING,	/* No components present */
	SetupRelease_1084P23_PR_release,
	SetupRelease_1084P23_PR_setup
} SetupRelease_1084P23_PR;
typedef enum SetupRelease_1084P24_PR {
	SetupRelease_1084P24_PR_NOTHING,	/* No components present */
	SetupRelease_1084P24_PR_release,
	SetupRelease_1084P24_PR_setup
} SetupRelease_1084P24_PR;
typedef enum SetupRelease_1084P25_PR {
	SetupRelease_1084P25_PR_NOTHING,	/* No components present */
	SetupRelease_1084P25_PR_release,
	SetupRelease_1084P25_PR_setup
} SetupRelease_1084P25_PR;
typedef enum SetupRelease_1084P26_PR {
	SetupRelease_1084P26_PR_NOTHING,	/* No components present */
	SetupRelease_1084P26_PR_release,
	SetupRelease_1084P26_PR_setup
} SetupRelease_1084P26_PR;
typedef enum SetupRelease_1084P27_PR {
	SetupRelease_1084P27_PR_NOTHING,	/* No components present */
	SetupRelease_1084P27_PR_release,
	SetupRelease_1084P27_PR_setup
} SetupRelease_1084P27_PR;
typedef enum SetupRelease_1084P28_PR {
	SetupRelease_1084P28_PR_NOTHING,	/* No components present */
	SetupRelease_1084P28_PR_release,
	SetupRelease_1084P28_PR_setup
} SetupRelease_1084P28_PR;
typedef enum SetupRelease_1084P29_PR {
	SetupRelease_1084P29_PR_NOTHING,	/* No components present */
	SetupRelease_1084P29_PR_release,
	SetupRelease_1084P29_PR_setup
} SetupRelease_1084P29_PR;
typedef enum SetupRelease_1084P30_PR {
	SetupRelease_1084P30_PR_NOTHING,	/* No components present */
	SetupRelease_1084P30_PR_release,
	SetupRelease_1084P30_PR_setup
} SetupRelease_1084P30_PR;
typedef enum SetupRelease_1084P31_PR {
	SetupRelease_1084P31_PR_NOTHING,	/* No components present */
	SetupRelease_1084P31_PR_release,
	SetupRelease_1084P31_PR_setup
} SetupRelease_1084P31_PR;
typedef enum SetupRelease_1084P32_PR {
	SetupRelease_1084P32_PR_NOTHING,	/* No components present */
	SetupRelease_1084P32_PR_release,
	SetupRelease_1084P32_PR_setup
} SetupRelease_1084P32_PR;
typedef enum SetupRelease_1084P33_PR {
	SetupRelease_1084P33_PR_NOTHING,	/* No components present */
	SetupRelease_1084P33_PR_release,
	SetupRelease_1084P33_PR_setup
} SetupRelease_1084P33_PR;
typedef enum SetupRelease_1084P34_PR {
	SetupRelease_1084P34_PR_NOTHING,	/* No components present */
	SetupRelease_1084P34_PR_release,
	SetupRelease_1084P34_PR_setup
} SetupRelease_1084P34_PR;
typedef enum SetupRelease_1084P35_PR {
	SetupRelease_1084P35_PR_NOTHING,	/* No components present */
	SetupRelease_1084P35_PR_release,
	SetupRelease_1084P35_PR_setup
} SetupRelease_1084P35_PR;
typedef enum SetupRelease_1084P36_PR {
	SetupRelease_1084P36_PR_NOTHING,	/* No components present */
	SetupRelease_1084P36_PR_release,
	SetupRelease_1084P36_PR_setup
} SetupRelease_1084P36_PR;
typedef enum SetupRelease_1084P37_PR {
	SetupRelease_1084P37_PR_NOTHING,	/* No components present */
	SetupRelease_1084P37_PR_release,
	SetupRelease_1084P37_PR_setup
} SetupRelease_1084P37_PR;
typedef enum SetupRelease_1084P38_PR {
	SetupRelease_1084P38_PR_NOTHING,	/* No components present */
	SetupRelease_1084P38_PR_release,
	SetupRelease_1084P38_PR_setup
} SetupRelease_1084P38_PR;
typedef enum SetupRelease_1084P39_PR {
	SetupRelease_1084P39_PR_NOTHING,	/* No components present */
	SetupRelease_1084P39_PR_release,
	SetupRelease_1084P39_PR_setup
} SetupRelease_1084P39_PR;
typedef enum SetupRelease_1084P40_PR {
	SetupRelease_1084P40_PR_NOTHING,	/* No components present */
	SetupRelease_1084P40_PR_release,
	SetupRelease_1084P40_PR_setup
} SetupRelease_1084P40_PR;
typedef enum SetupRelease_1084P41_PR {
	SetupRelease_1084P41_PR_NOTHING,	/* No components present */
	SetupRelease_1084P41_PR_release,
	SetupRelease_1084P41_PR_setup
} SetupRelease_1084P41_PR;
typedef enum SetupRelease_1084P42_PR {
	SetupRelease_1084P42_PR_NOTHING,	/* No components present */
	SetupRelease_1084P42_PR_release,
	SetupRelease_1084P42_PR_setup
} SetupRelease_1084P42_PR;
typedef enum SetupRelease_1084P43_PR {
	SetupRelease_1084P43_PR_NOTHING,	/* No components present */
	SetupRelease_1084P43_PR_release,
	SetupRelease_1084P43_PR_setup
} SetupRelease_1084P43_PR;
typedef enum SetupRelease_1084P44_PR {
	SetupRelease_1084P44_PR_NOTHING,	/* No components present */
	SetupRelease_1084P44_PR_release,
	SetupRelease_1084P44_PR_setup
} SetupRelease_1084P44_PR;
typedef enum SetupRelease_1084P45_PR {
	SetupRelease_1084P45_PR_NOTHING,	/* No components present */
	SetupRelease_1084P45_PR_release,
	SetupRelease_1084P45_PR_setup
} SetupRelease_1084P45_PR;
typedef enum SetupRelease_1084P46_PR {
	SetupRelease_1084P46_PR_NOTHING,	/* No components present */
	SetupRelease_1084P46_PR_release,
	SetupRelease_1084P46_PR_setup
} SetupRelease_1084P46_PR;
typedef enum SetupRelease_1084P47_PR {
	SetupRelease_1084P47_PR_NOTHING,	/* No components present */
	SetupRelease_1084P47_PR_release,
	SetupRelease_1084P47_PR_setup
} SetupRelease_1084P47_PR;
typedef enum SetupRelease_1084P48_PR {
	SetupRelease_1084P48_PR_NOTHING,	/* No components present */
	SetupRelease_1084P48_PR_release,
	SetupRelease_1084P48_PR_setup
} SetupRelease_1084P48_PR;
typedef enum SetupRelease_1084P49_PR {
	SetupRelease_1084P49_PR_NOTHING,	/* No components present */
	SetupRelease_1084P49_PR_release,
	SetupRelease_1084P49_PR_setup
} SetupRelease_1084P49_PR;
typedef enum SetupRelease_1084P50_PR {
	SetupRelease_1084P50_PR_NOTHING,	/* No components present */
	SetupRelease_1084P50_PR_release,
	SetupRelease_1084P50_PR_setup
} SetupRelease_1084P50_PR;
typedef enum SetupRelease_1084P51_PR {
	SetupRelease_1084P51_PR_NOTHING,	/* No components present */
	SetupRelease_1084P51_PR_release,
	SetupRelease_1084P51_PR_setup
} SetupRelease_1084P51_PR;
typedef enum SetupRelease_1084P52_PR {
	SetupRelease_1084P52_PR_NOTHING,	/* No components present */
	SetupRelease_1084P52_PR_release,
	SetupRelease_1084P52_PR_setup
} SetupRelease_1084P52_PR;

/* Forward declarations */
struct LocationMeasurementInfo;
struct MRDC_SecondaryCellGroupConfig;
struct PDCCH_ConfigCommon;
struct PDSCH_ConfigCommon;
struct PDCCH_Config;
struct PDSCH_Config;
struct SPS_Config;
struct RadioLinkMonitoringConfig;
struct RACH_ConfigCommon;
struct PUSCH_ConfigCommon;
struct PUCCH_ConfigCommon;
struct PUCCH_Config;
struct PUSCH_Config;
struct ConfiguredGrantConfig;
struct SRS_Config;
struct BeamFailureRecoveryConfig;
struct RLF_TimersAndConstants;
struct CG_UCI_OnPUSCH;
struct CSI_AperiodicTriggerStateList;
struct CSI_SemiPersistentOnPUSCH_TriggerStateList;
struct PTRS_DownlinkConfig;
struct PTRS_UplinkConfig;
struct DRX_Config;
struct PHR_Config;
struct GapConfig;
struct CSI_RS_ResourceConfigMobility;
struct SSB_ToMeasure;
struct DownlinkPreemption;
struct PUSCH_TPC_CommandConfig;
struct PUCCH_TPC_CommandConfig;
struct SRS_TPC_CommandConfig;
struct SlotFormatIndicator;
struct DMRS_DownlinkConfig;
struct PDSCH_TimeDomainResourceAllocationList;
struct ZP_CSI_RS_ResourceSet;
struct PDSCH_CodeBlockGroupTransmission;
struct PUCCH_FormatConfig;
struct DMRS_UplinkConfig;
struct PUSCH_TimeDomainResourceAllocationList;
struct UCI_OnPUSCH;
struct PUSCH_CodeBlockGroupTransmission;
struct PDCCH_ServingCellConfig;
struct PDSCH_ServingCellConfig;
struct CSI_MeasConfig;
struct RateMatchPatternLTE_CRS;
struct PUSCH_ServingCellConfig;
struct SRS_CarrierSwitching;
struct OverheatingAssistanceConfig;

/* SetupRelease */
typedef struct SetupRelease_1084P0 {
	SetupRelease_1084P0_PR present;
	union SetupRelease_1084P0_u {
		NULL_t	 release;
		struct LocationMeasurementInfo	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P0_t;
typedef struct SetupRelease_1084P1 {
	SetupRelease_1084P1_PR present;
	union SetupRelease_1084P1_u {
		NULL_t	 release;
		struct MRDC_SecondaryCellGroupConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P1_t;
typedef struct SetupRelease_1084P2 {
	SetupRelease_1084P2_PR present;
	union SetupRelease_1084P2_u {
		NULL_t	 release;
		struct PDCCH_ConfigCommon	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P2_t;
typedef struct SetupRelease_1084P3 {
	SetupRelease_1084P3_PR present;
	union SetupRelease_1084P3_u {
		NULL_t	 release;
		struct PDSCH_ConfigCommon	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P3_t;
typedef struct SetupRelease_1084P4 {
	SetupRelease_1084P4_PR present;
	union SetupRelease_1084P4_u {
		NULL_t	 release;
		struct PDCCH_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P4_t;
typedef struct SetupRelease_1084P5 {
	SetupRelease_1084P5_PR present;
	union SetupRelease_1084P5_u {
		NULL_t	 release;
		struct PDSCH_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P5_t;
typedef struct SetupRelease_1084P6 {
	SetupRelease_1084P6_PR present;
	union SetupRelease_1084P6_u {
		NULL_t	 release;
		struct SPS_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P6_t;
typedef struct SetupRelease_1084P7 {
	SetupRelease_1084P7_PR present;
	union SetupRelease_1084P7_u {
		NULL_t	 release;
		struct RadioLinkMonitoringConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P7_t;
typedef struct SetupRelease_1084P8 {
	SetupRelease_1084P8_PR present;
	union SetupRelease_1084P8_u {
		NULL_t	 release;
		struct RACH_ConfigCommon	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P8_t;
typedef struct SetupRelease_1084P9 {
	SetupRelease_1084P9_PR present;
	union SetupRelease_1084P9_u {
		NULL_t	 release;
		struct PUSCH_ConfigCommon	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P9_t;
typedef struct SetupRelease_1084P10 {
	SetupRelease_1084P10_PR present;
	union SetupRelease_1084P10_u {
		NULL_t	 release;
		struct PUCCH_ConfigCommon	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P10_t;
typedef struct SetupRelease_1084P11 {
	SetupRelease_1084P11_PR present;
	union SetupRelease_1084P11_u {
		NULL_t	 release;
		struct PUCCH_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P11_t;
typedef struct SetupRelease_1084P12 {
	SetupRelease_1084P12_PR present;
	union SetupRelease_1084P12_u {
		NULL_t	 release;
		struct PUSCH_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P12_t;
typedef struct SetupRelease_1084P13 {
	SetupRelease_1084P13_PR present;
	union SetupRelease_1084P13_u {
		NULL_t	 release;
		struct ConfiguredGrantConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P13_t;
typedef struct SetupRelease_1084P14 {
	SetupRelease_1084P14_PR present;
	union SetupRelease_1084P14_u {
		NULL_t	 release;
		struct SRS_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P14_t;
typedef struct SetupRelease_1084P15 {
	SetupRelease_1084P15_PR present;
	union SetupRelease_1084P15_u {
		NULL_t	 release;
		struct BeamFailureRecoveryConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P15_t;
typedef struct SetupRelease_1084P16 {
	SetupRelease_1084P16_PR present;
	union SetupRelease_1084P16_u {
		NULL_t	 release;
		struct RLF_TimersAndConstants	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P16_t;
typedef struct SetupRelease_1084P17 {
	SetupRelease_1084P17_PR present;
	union SetupRelease_1084P17_u {
		NULL_t	 release;
		struct CG_UCI_OnPUSCH	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P17_t;
typedef struct SetupRelease_1084P18 {
	SetupRelease_1084P18_PR present;
	union SetupRelease_1084P18_u {
		NULL_t	 release;
		struct CSI_AperiodicTriggerStateList	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P18_t;
typedef struct SetupRelease_1084P19 {
	SetupRelease_1084P19_PR present;
	union SetupRelease_1084P19_u {
		NULL_t	 release;
		struct CSI_SemiPersistentOnPUSCH_TriggerStateList	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P19_t;
typedef struct SetupRelease_1084P20 {
	SetupRelease_1084P20_PR present;
	union SetupRelease_1084P20_u {
		NULL_t	 release;
		struct PTRS_DownlinkConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P20_t;
typedef struct SetupRelease_1084P21 {
	SetupRelease_1084P21_PR present;
	union SetupRelease_1084P21_u {
		NULL_t	 release;
		struct PTRS_UplinkConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P21_t;
typedef struct SetupRelease_1084P22 {
	SetupRelease_1084P22_PR present;
	union SetupRelease_1084P22_u {
		NULL_t	 release;
		struct DRX_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P22_t;
typedef struct SetupRelease_1084P23 {
	SetupRelease_1084P23_PR present;
	union SetupRelease_1084P23_u {
		NULL_t	 release;
		struct PHR_Config	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P23_t;
typedef struct SetupRelease_1084P24 {
	SetupRelease_1084P24_PR present;
	union SetupRelease_1084P24_u {
		NULL_t	 release;
		DataInactivityTimer_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P24_t;
typedef struct SetupRelease_1084P25 {
	SetupRelease_1084P25_PR present;
	union SetupRelease_1084P25_u {
		NULL_t	 release;
		struct GapConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P25_t;
typedef struct SetupRelease_1084P26 {
	SetupRelease_1084P26_PR present;
	union SetupRelease_1084P26_u {
		NULL_t	 release;
		MeasGapSharingScheme_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P26_t;
typedef struct SetupRelease_1084P27 {
	SetupRelease_1084P27_PR present;
	union SetupRelease_1084P27_u {
		NULL_t	 release;
		struct CSI_RS_ResourceConfigMobility	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P27_t;
typedef struct SetupRelease_1084P28 {
	SetupRelease_1084P28_PR present;
	union SetupRelease_1084P28_u {
		NULL_t	 release;
		struct SSB_ToMeasure	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P28_t;
typedef struct SetupRelease_1084P29 {
	SetupRelease_1084P29_PR present;
	union SetupRelease_1084P29_u {
		NULL_t	 release;
		struct DownlinkPreemption	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P29_t;
typedef struct SetupRelease_1084P30 {
	SetupRelease_1084P30_PR present;
	union SetupRelease_1084P30_u {
		NULL_t	 release;
		struct PUSCH_TPC_CommandConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P30_t;
typedef struct SetupRelease_1084P31 {
	SetupRelease_1084P31_PR present;
	union SetupRelease_1084P31_u {
		NULL_t	 release;
		struct PUCCH_TPC_CommandConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P31_t;
typedef struct SetupRelease_1084P32 {
	SetupRelease_1084P32_PR present;
	union SetupRelease_1084P32_u {
		NULL_t	 release;
		struct SRS_TPC_CommandConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P32_t;
typedef struct SetupRelease_1084P33 {
	SetupRelease_1084P33_PR present;
	union SetupRelease_1084P33_u {
		NULL_t	 release;
		struct SlotFormatIndicator	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P33_t;
typedef struct SetupRelease_1084P34 {
	SetupRelease_1084P34_PR present;
	union SetupRelease_1084P34_u {
		NULL_t	 release;
		struct DMRS_DownlinkConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P34_t;
typedef struct SetupRelease_1084P35 {
	SetupRelease_1084P35_PR present;
	union SetupRelease_1084P35_u {
		NULL_t	 release;
		struct PDSCH_TimeDomainResourceAllocationList	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P35_t;
typedef struct SetupRelease_1084P36 {
	SetupRelease_1084P36_PR present;
	union SetupRelease_1084P36_u {
		NULL_t	 release;
		struct ZP_CSI_RS_ResourceSet	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P36_t;
typedef struct SetupRelease_1084P37 {
	SetupRelease_1084P37_PR present;
	union SetupRelease_1084P37_u {
		NULL_t	 release;
		struct PDSCH_CodeBlockGroupTransmission	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P37_t;
typedef struct SetupRelease_1084P38 {
	SetupRelease_1084P38_PR present;
	union SetupRelease_1084P38_u {
		NULL_t	 release;
		RNTI_Value_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P38_t;
typedef struct SetupRelease_1084P39 {
	SetupRelease_1084P39_PR present;
	union SetupRelease_1084P39_u {
		NULL_t	 release;
		PDCCH_BlindDetection_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P39_t;
typedef struct SetupRelease_1084P40 {
	SetupRelease_1084P40_PR present;
	union SetupRelease_1084P40_u {
		NULL_t	 release;
		struct PUCCH_FormatConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P40_t;
typedef struct SetupRelease_1084P41 {
	SetupRelease_1084P41_PR present;
	union SetupRelease_1084P41_u {
		NULL_t	 release;
		struct DMRS_UplinkConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P41_t;
typedef struct SetupRelease_1084P42 {
	SetupRelease_1084P42_PR present;
	union SetupRelease_1084P42_u {
		NULL_t	 release;
		struct PUSCH_TimeDomainResourceAllocationList	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P42_t;
typedef struct SetupRelease_1084P43 {
	SetupRelease_1084P43_PR present;
	union SetupRelease_1084P43_u {
		NULL_t	 release;
		struct UCI_OnPUSCH	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P43_t;
typedef struct SetupRelease_1084P44 {
	SetupRelease_1084P44_PR present;
	union SetupRelease_1084P44_u {
		NULL_t	 release;
		struct PUSCH_CodeBlockGroupTransmission	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P44_t;
typedef struct SetupRelease_1084P45 {
	SetupRelease_1084P45_PR present;
	union SetupRelease_1084P45_u {
		NULL_t	 release;
		struct PDCCH_ServingCellConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P45_t;
typedef struct SetupRelease_1084P46 {
	SetupRelease_1084P46_PR present;
	union SetupRelease_1084P46_u {
		NULL_t	 release;
		struct PDSCH_ServingCellConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P46_t;
typedef struct SetupRelease_1084P47 {
	SetupRelease_1084P47_PR present;
	union SetupRelease_1084P47_u {
		NULL_t	 release;
		struct CSI_MeasConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P47_t;
typedef struct SetupRelease_1084P48 {
	SetupRelease_1084P48_PR present;
	union SetupRelease_1084P48_u {
		NULL_t	 release;
		struct RateMatchPatternLTE_CRS	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P48_t;
typedef struct SetupRelease_1084P49 {
	SetupRelease_1084P49_PR present;
	union SetupRelease_1084P49_u {
		NULL_t	 release;
		struct PUSCH_ServingCellConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P49_t;
typedef struct SetupRelease_1084P50 {
	SetupRelease_1084P50_PR present;
	union SetupRelease_1084P50_u {
		NULL_t	 release;
		struct SRS_CarrierSwitching	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P50_t;
typedef struct SetupRelease_1084P51 {
	SetupRelease_1084P51_PR present;
	union SetupRelease_1084P51_u {
		NULL_t	 release;
		struct OverheatingAssistanceConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P51_t;
typedef struct SetupRelease_1084P52 {
	SetupRelease_1084P52_PR present;
	union SetupRelease_1084P52_u {
		NULL_t	 release;
		struct GapConfig	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1084P52_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P0;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P0_specs_1;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P0_1[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P1;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P1_specs_4;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P1_4[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P1_constr_4;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P2;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P2_specs_7;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P2_7[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P2_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P3;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P3_specs_10;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P3_10[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P3_constr_10;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P4;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P4_specs_13;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P4_13[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P4_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P5;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P5_specs_16;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P5_16[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P5_constr_16;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P6;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P6_specs_19;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P6_19[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P6_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P7;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P7_specs_22;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P7_22[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P7_constr_22;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P8;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P8_specs_25;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P8_25[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P8_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P9;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P9_specs_28;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P9_28[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P9_constr_28;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P10;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P10_specs_31;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P10_31[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P10_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P11;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P11_specs_34;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P11_34[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P11_constr_34;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P12;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P12_specs_37;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P12_37[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P12_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P13;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P13_specs_40;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P13_40[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P13_constr_40;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P14;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P14_specs_43;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P14_43[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P14_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P15;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P15_specs_46;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P15_46[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P15_constr_46;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P16_specs_49;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P16_49[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P16_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P17;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P17_specs_52;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P17_52[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P17_constr_52;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P18;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P18_specs_55;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P18_55[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P18_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P19;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P19_specs_58;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P19_58[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P19_constr_58;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P20;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P20_specs_61;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P20_61[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P20_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P21;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P21_specs_64;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P21_64[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P21_constr_64;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P22;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P22_specs_67;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P22_67[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P22_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P23;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P23_specs_70;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P23_70[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P23_constr_70;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P24;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P24_specs_73;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P24_73[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P24_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P25;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P25_specs_76;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P25_76[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P25_constr_76;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P26;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P26_specs_79;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P26_79[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P26_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P27;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P27_specs_82;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P27_82[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P27_constr_82;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P28;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P28_specs_85;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P28_85[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P28_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P29;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P29_specs_88;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P29_88[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P29_constr_88;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P30;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P30_specs_91;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P30_91[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P30_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P31;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P31_specs_94;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P31_94[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P31_constr_94;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P32;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P32_specs_97;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P32_97[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P32_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P33;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P33_specs_100;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P33_100[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P33_constr_100;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P34;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P34_specs_103;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P34_103[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P34_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P35;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P35_specs_106;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P35_106[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P35_constr_106;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P36;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P36_specs_109;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P36_109[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P36_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P37;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P37_specs_112;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P37_112[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P37_constr_112;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P38;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P38_specs_115;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P38_115[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P38_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P39;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P39_specs_118;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P39_118[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P39_constr_118;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P40;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P40_specs_121;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P40_121[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P40_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P41;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P41_specs_124;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P41_124[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P41_constr_124;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P42;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P42_specs_127;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P42_127[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P42_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P43;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P43_specs_130;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P43_130[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P43_constr_130;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P44;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P44_specs_133;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P44_133[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P44_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P45;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P45_specs_136;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P45_136[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P45_constr_136;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P46;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P46_specs_139;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P46_139[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P46_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P47;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P47_specs_142;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P47_142[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P47_constr_142;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P48;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P48_specs_145;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P48_145[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P48_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P49;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P49_specs_148;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P49_148[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P49_constr_148;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P50;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P50_specs_151;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P50_151[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P50_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P51;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P51_specs_154;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P51_154[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P51_constr_154;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1084P52;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1084P52_specs_157;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1084P52_157[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1084P52_constr_157;

#ifdef __cplusplus
}
#endif

#endif	/* _SetupRelease_H_ */
#include <asn_internal.h>
