/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CA_ParametersNR_v15g0_H_
#define	_CA_ParametersNR_v15g0_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SimultaneousRxTxPerBandPair.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CA-ParametersNR-v15g0 */
typedef struct CA_ParametersNR_v15g0 {
	SimultaneousRxTxPerBandPair_t	*simultaneousRxTxInterBandCAPerBandPair	/* OPTIONAL */;
	SimultaneousRxTxPerBandPair_t	*simultaneousRxTxSULPerBandPair	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNR_v15g0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNR_v15g0;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNR_v15g0_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNR_v15g0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CA_ParametersNR_v15g0_H_ */
#include <asn_internal.h>
