/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "MAC-CellGroupConfig.h"

#include "SetupRelease.h"
#include "SchedulingRequestConfig.h"
#include "BSR-Config.h"
#include "TAG-Config.h"
asn_TYPE_member_t asn_MBR_MAC_CellGroupConfig_1[] = {
	{ ATF_POINTER, 5, offsetof(struct MAC_CellGroupConfig, drx_Config),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drx-Config"
		},
	{ ATF_POINTER, 4, offsetof(struct MAC_CellGroupConfig, schedulingRequestConfig),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SchedulingRequestConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedulingRequestConfig"
		},
	{ ATF_POINTER, 3, offsetof(struct MAC_CellGroupConfig, bsr_Config),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSR_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bsr-Config"
		},
	{ ATF_POINTER, 2, offsetof(struct MAC_CellGroupConfig, tag_Config),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAG_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tag-Config"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_CellGroupConfig, phr_Config),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"phr-Config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_CellGroupConfig, skipUplinkTxDynamic),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"skipUplinkTxDynamic"
		},
	{ ATF_POINTER, 2, offsetof(struct MAC_CellGroupConfig, csi_Mask),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-Mask"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_CellGroupConfig, dataInactivityTimer),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataInactivityTimer"
		},
};
static const int asn_MAP_MAC_CellGroupConfig_oms_1[] = { 0, 1, 2, 3, 4, 6, 7 };
static const ber_tlv_tag_t asn_DEF_MAC_CellGroupConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MAC_CellGroupConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* drx-Config */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* schedulingRequestConfig */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bsr-Config */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* tag-Config */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* phr-Config */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* skipUplinkTxDynamic */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* csi-Mask */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* dataInactivityTimer */
};
asn_SEQUENCE_specifics_t asn_SPC_MAC_CellGroupConfig_specs_1 = {
	sizeof(struct MAC_CellGroupConfig),
	offsetof(struct MAC_CellGroupConfig, _asn_ctx),
	asn_MAP_MAC_CellGroupConfig_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_MAC_CellGroupConfig_oms_1,	/* Optional members */
	5, 2,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MAC_CellGroupConfig = {
	"MAC-CellGroupConfig",
	"MAC-CellGroupConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_MAC_CellGroupConfig_tags_1,
	sizeof(asn_DEF_MAC_CellGroupConfig_tags_1)
		/sizeof(asn_DEF_MAC_CellGroupConfig_tags_1[0]), /* 1 */
	asn_DEF_MAC_CellGroupConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_MAC_CellGroupConfig_tags_1)
		/sizeof(asn_DEF_MAC_CellGroupConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MAC_CellGroupConfig_1,
	8,	/* Elements count */
	&asn_SPC_MAC_CellGroupConfig_specs_1	/* Additional specs */
};

