/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "MeasGapConfig.h"

#include "SetupRelease.h"
asn_TYPE_member_t asn_MBR_MeasGapConfig_1[] = {
	{ ATF_POINTER, 3, offsetof(struct MeasGapConfig, gapFR2),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P25,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gapFR2"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasGapConfig, gapFR1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P25,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gapFR1"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasGapConfig, gapUE),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P25,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gapUE"
		},
};
static const int asn_MAP_MeasGapConfig_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_MeasGapConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasGapConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gapFR2 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gapFR1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gapUE */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasGapConfig_specs_1 = {
	sizeof(struct MeasGapConfig),
	offsetof(struct MeasGapConfig, _asn_ctx),
	asn_MAP_MeasGapConfig_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasGapConfig_oms_1,	/* Optional members */
	1, 2,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasGapConfig = {
	"MeasGapConfig",
	"MeasGapConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasGapConfig_tags_1,
	sizeof(asn_DEF_MeasGapConfig_tags_1)
		/sizeof(asn_DEF_MeasGapConfig_tags_1[0]), /* 1 */
	asn_DEF_MeasGapConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasGapConfig_tags_1)
		/sizeof(asn_DEF_MeasGapConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasGapConfig_1,
	3,	/* Elements count */
	&asn_SPC_MeasGapConfig_specs_1	/* Additional specs */
};

