/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SCGFailureInformation_IEs_H_
#define	_SCGFailureInformation_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FailureReportSCG;
struct SCGFailureInformation_v1590_IEs;

/* SCGFailureInformation-IEs */
typedef struct SCGFailureInformation_IEs {
	struct FailureReportSCG	*failureReportSCG	/* OPTIONAL */;
	struct SCGFailureInformation_v1590_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCGFailureInformation_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCGFailureInformation_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SCGFailureInformation_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SCGFailureInformation_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SCGFailureInformation_IEs_H_ */
#include <asn_internal.h>
