/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SelectedBandEntriesMN_H_
#define	_SelectedBandEntriesMN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BandEntryIndex.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SelectedBandEntriesMN */
typedef struct SelectedBandEntriesMN {
	A_SEQUENCE_OF(BandEntryIndex_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SelectedBandEntriesMN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SelectedBandEntriesMN;
extern asn_SET_OF_specifics_t asn_SPC_SelectedBandEntriesMN_specs_1;
extern asn_TYPE_member_t asn_MBR_SelectedBandEntriesMN_1[1];
extern asn_per_constraints_t asn_PER_type_SelectedBandEntriesMN_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SelectedBandEntriesMN_H_ */
#include <asn_internal.h>
