/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UE_NR_Capability_v1570_H_
#define	_UE_NR_Capability_v1570_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRDC_Parameters_v1570;

/* UE-NR-Capability-v1570 */
typedef struct UE_NR_Capability_v1570 {
	struct NRDC_Parameters_v1570	*nrdc_Parameters_v1570	/* OPTIONAL */;
	struct UE_NR_Capability_v1570__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_NR_Capability_v1570_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_NR_Capability_v1570;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_NR_Capability_v1570_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_NR_Capability_v1570_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_NR_Capability_v1570_H_ */
#include <asn_internal.h>
