/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UERadioPagingInformation_v15e0_IEs_H_
#define	_UERadioPagingInformation_v15e0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_FDD_FR1 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_FDD_FR1_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_FDD_FR1;
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR1 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR1_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR1;
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR2 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR2_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeA_TDD_FR2;
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_FDD_FR1 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_FDD_FR1_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_FDD_FR1;
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR1 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR1_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR1;
typedef enum UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR2 {
	UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR2_supported	= 0
} e_UERadioPagingInformation_v15e0_IEs__dl_SchedulingOffset_PDSCH_TypeB_TDD_FR2;

/* UERadioPagingInformation-v15e0-IEs */
typedef struct UERadioPagingInformation_v15e0_IEs {
	long	*dl_SchedulingOffset_PDSCH_TypeA_FDD_FR1	/* OPTIONAL */;
	long	*dl_SchedulingOffset_PDSCH_TypeA_TDD_FR1	/* OPTIONAL */;
	long	*dl_SchedulingOffset_PDSCH_TypeA_TDD_FR2	/* OPTIONAL */;
	long	*dl_SchedulingOffset_PDSCH_TypeB_FDD_FR1	/* OPTIONAL */;
	long	*dl_SchedulingOffset_PDSCH_TypeB_TDD_FR1	/* OPTIONAL */;
	long	*dl_SchedulingOffset_PDSCH_TypeB_TDD_FR2	/* OPTIONAL */;
	struct UERadioPagingInformation_v15e0_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERadioPagingInformation_v15e0_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeA_FDD_FR1_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeA_TDD_FR1_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeA_TDD_FR2_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeB_FDD_FR1_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeB_TDD_FR1_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_SchedulingOffset_PDSCH_TypeB_TDD_FR2_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UERadioPagingInformation_v15e0_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UERadioPagingInformation_v15e0_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UERadioPagingInformation_v15e0_IEs_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _UERadioPagingInformation_v15e0_IEs_H_ */
#include <asn_internal.h>
