/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "AS-Context.h"

#include "ReestablishmentInfo.h"
#include "ConfigRestrictInfoSCG.h"
#include "RAN-NotificationAreaInfo.h"
#include "BandCombinationInfoSN.h"
static int
memb_ueAssistanceInformation_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)st; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_ueAssistanceInformation_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_ueAssistanceInformation_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AS_Context_1[] = {
	{ ATF_POINTER, 5, offsetof(struct AS_Context, reestablishmentInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReestablishmentInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reestablishmentInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct AS_Context, configRestrictInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConfigRestrictInfoSCG,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"configRestrictInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct AS_Context, ran_NotificationAreaInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RAN_NotificationAreaInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ran-NotificationAreaInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct AS_Context, ueAssistanceInformation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_ueAssistanceInformation_constr_6, &asn_PER_memb_ueAssistanceInformation_constr_6,  memb_ueAssistanceInformation_constraint_1 },
		0, 0, /* No default value */
		"ueAssistanceInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct AS_Context, selectedBandCombinationSN),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationInfoSN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"selectedBandCombinationSN"
		},
};
static const int asn_MAP_AS_Context_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_AS_Context_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AS_Context_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reestablishmentInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* configRestrictInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ran-NotificationAreaInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ueAssistanceInformation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* selectedBandCombinationSN */
};
asn_SEQUENCE_specifics_t asn_SPC_AS_Context_specs_1 = {
	sizeof(struct AS_Context),
	offsetof(struct AS_Context, _asn_ctx),
	asn_MAP_AS_Context_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_AS_Context_oms_1,	/* Optional members */
	2, 3,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AS_Context = {
	"AS-Context",
	"AS-Context",
	&asn_OP_SEQUENCE,
	asn_DEF_AS_Context_tags_1,
	sizeof(asn_DEF_AS_Context_tags_1)
		/sizeof(asn_DEF_AS_Context_tags_1[0]), /* 1 */
	asn_DEF_AS_Context_tags_1,	/* Same as above */
	sizeof(asn_DEF_AS_Context_tags_1)
		/sizeof(asn_DEF_AS_Context_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AS_Context_1,
	5,	/* Elements count */
	&asn_SPC_AS_Context_specs_1	/* Additional specs */
};

