/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CG_ConfigInfo_v1570_IEs_H_
#define	_CG_ConfigInfo_v1570_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SFTD_FrequencyList_NR;
struct SFTD_FrequencyList_EUTRA;
struct CG_ConfigInfo_v1590_IEs;

/* CG-ConfigInfo-v1570-IEs */
typedef struct CG_ConfigInfo_v1570_IEs {
	struct SFTD_FrequencyList_NR	*sftdFrequencyList_NR	/* OPTIONAL */;
	struct SFTD_FrequencyList_EUTRA	*sftdFrequencyList_EUTRA	/* OPTIONAL */;
	struct CG_ConfigInfo_v1590_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CG_ConfigInfo_v1570_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CG_ConfigInfo_v1570_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_CG_ConfigInfo_v1570_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_CG_ConfigInfo_v1570_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CG_ConfigInfo_v1570_IEs_H_ */
#include <asn_internal.h>
