/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NRDC_Parameters_v15c0_H_
#define	_NRDC_Parameters_v15c0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRDC_Parameters_v15c0__pdcp_DuplicationSplitSRB {
	NRDC_Parameters_v15c0__pdcp_DuplicationSplitSRB_supported	= 0
} e_NRDC_Parameters_v15c0__pdcp_DuplicationSplitSRB;
typedef enum NRDC_Parameters_v15c0__pdcp_DuplicationSplitDRB {
	NRDC_Parameters_v15c0__pdcp_DuplicationSplitDRB_supported	= 0
} e_NRDC_Parameters_v15c0__pdcp_DuplicationSplitDRB;

/* NRDC-Parameters-v15c0 */
typedef struct NRDC_Parameters_v15c0 {
	long	*pdcp_DuplicationSplitSRB	/* OPTIONAL */;
	long	*pdcp_DuplicationSplitDRB	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRDC_Parameters_v15c0_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_pdcp_DuplicationSplitSRB_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pdcp_DuplicationSplitDRB_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRDC_Parameters_v15c0;
extern asn_SEQUENCE_specifics_t asn_SPC_NRDC_Parameters_v15c0_specs_1;
extern asn_TYPE_member_t asn_MBR_NRDC_Parameters_v15c0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NRDC_Parameters_v15c0_H_ */
#include <asn_internal.h>
