/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UE_MRDC_Capability_v15g0_H_
#define	_UE_MRDC_Capability_v15g0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RF_ParametersMRDC_v15g0;

/* UE-MRDC-Capability-v15g0 */
typedef struct UE_MRDC_Capability_v15g0 {
	struct RF_ParametersMRDC_v15g0	*rf_ParametersMRDC_v15g0	/* OPTIONAL */;
	struct UE_MRDC_Capability_v15g0__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_MRDC_Capability_v15g0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_MRDC_Capability_v15g0;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_MRDC_Capability_v15g0_H_ */
#include <asn_internal.h>
