/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "UplinkConfig.h"

#include "BWP-UplinkDedicated.h"
#include "SetupRelease.h"
#include "BWP-Uplink.h"
#include "SCS-SpecificCarrier.h"
static int
memb_uplinkBWP_ToReleaseList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_uplinkBWP_ToAddModList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_uplinkChannelBW_PerSCS_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 5)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_uplinkBWP_ToReleaseList_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_uplinkBWP_ToReleaseList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_uplinkBWP_ToAddModList_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_uplinkBWP_ToAddModList_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_uplinkChannelBW_PerSCS_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..5)) */};
static asn_per_constraints_t asn_PER_type_uplinkChannelBW_PerSCS_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  5 }	/* (SIZE(1..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_uplinkBWP_ToReleaseList_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_uplinkBWP_ToReleaseList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_uplinkBWP_ToAddModList_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_uplinkBWP_ToAddModList_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_uplinkChannelBW_PerSCS_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..5)) */};
static asn_per_constraints_t asn_PER_memb_uplinkChannelBW_PerSCS_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  5 }	/* (SIZE(1..5)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_uplinkBWP_ToReleaseList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_BWP_Id,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_uplinkBWP_ToReleaseList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_uplinkBWP_ToReleaseList_specs_3 = {
	sizeof(struct UplinkConfig__uplinkBWP_ToReleaseList),
	offsetof(struct UplinkConfig__uplinkBWP_ToReleaseList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_uplinkBWP_ToReleaseList_3 = {
	"uplinkBWP-ToReleaseList",
	"uplinkBWP-ToReleaseList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_uplinkBWP_ToReleaseList_tags_3,
	sizeof(asn_DEF_uplinkBWP_ToReleaseList_tags_3)
		/sizeof(asn_DEF_uplinkBWP_ToReleaseList_tags_3[0]) - 1, /* 1 */
	asn_DEF_uplinkBWP_ToReleaseList_tags_3,	/* Same as above */
	sizeof(asn_DEF_uplinkBWP_ToReleaseList_tags_3)
		/sizeof(asn_DEF_uplinkBWP_ToReleaseList_tags_3[0]), /* 2 */
	{ &asn_OER_type_uplinkBWP_ToReleaseList_constr_3, &asn_PER_type_uplinkBWP_ToReleaseList_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_uplinkBWP_ToReleaseList_3,
	1,	/* Single element */
	&asn_SPC_uplinkBWP_ToReleaseList_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_uplinkBWP_ToAddModList_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BWP_Uplink,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_uplinkBWP_ToAddModList_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_uplinkBWP_ToAddModList_specs_5 = {
	sizeof(struct UplinkConfig__uplinkBWP_ToAddModList),
	offsetof(struct UplinkConfig__uplinkBWP_ToAddModList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_uplinkBWP_ToAddModList_5 = {
	"uplinkBWP-ToAddModList",
	"uplinkBWP-ToAddModList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_uplinkBWP_ToAddModList_tags_5,
	sizeof(asn_DEF_uplinkBWP_ToAddModList_tags_5)
		/sizeof(asn_DEF_uplinkBWP_ToAddModList_tags_5[0]) - 1, /* 1 */
	asn_DEF_uplinkBWP_ToAddModList_tags_5,	/* Same as above */
	sizeof(asn_DEF_uplinkBWP_ToAddModList_tags_5)
		/sizeof(asn_DEF_uplinkBWP_ToAddModList_tags_5[0]), /* 2 */
	{ &asn_OER_type_uplinkBWP_ToAddModList_constr_5, &asn_PER_type_uplinkBWP_ToAddModList_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_uplinkBWP_ToAddModList_5,
	1,	/* Single element */
	&asn_SPC_uplinkBWP_ToAddModList_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_uplinkChannelBW_PerSCS_List_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SCS_SpecificCarrier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_uplinkChannelBW_PerSCS_List_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_uplinkChannelBW_PerSCS_List_specs_12 = {
	sizeof(struct UplinkConfig__uplinkChannelBW_PerSCS_List),
	offsetof(struct UplinkConfig__uplinkChannelBW_PerSCS_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_uplinkChannelBW_PerSCS_List_12 = {
	"uplinkChannelBW-PerSCS-List",
	"uplinkChannelBW-PerSCS-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_uplinkChannelBW_PerSCS_List_tags_12,
	sizeof(asn_DEF_uplinkChannelBW_PerSCS_List_tags_12)
		/sizeof(asn_DEF_uplinkChannelBW_PerSCS_List_tags_12[0]) - 1, /* 1 */
	asn_DEF_uplinkChannelBW_PerSCS_List_tags_12,	/* Same as above */
	sizeof(asn_DEF_uplinkChannelBW_PerSCS_List_tags_12)
		/sizeof(asn_DEF_uplinkChannelBW_PerSCS_List_tags_12[0]), /* 2 */
	{ &asn_OER_type_uplinkChannelBW_PerSCS_List_constr_12, &asn_PER_type_uplinkChannelBW_PerSCS_List_constr_12, SEQUENCE_OF_constraint },
	asn_MBR_uplinkChannelBW_PerSCS_List_12,
	1,	/* Single element */
	&asn_SPC_uplinkChannelBW_PerSCS_List_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UplinkConfig_1[] = {
	{ ATF_POINTER, 8, offsetof(struct UplinkConfig, initialUplinkBWP),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BWP_UplinkDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialUplinkBWP"
		},
	{ ATF_POINTER, 7, offsetof(struct UplinkConfig, uplinkBWP_ToReleaseList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_uplinkBWP_ToReleaseList_3,
		0,
		{ &asn_OER_memb_uplinkBWP_ToReleaseList_constr_3, &asn_PER_memb_uplinkBWP_ToReleaseList_constr_3,  memb_uplinkBWP_ToReleaseList_constraint_1 },
		0, 0, /* No default value */
		"uplinkBWP-ToReleaseList"
		},
	{ ATF_POINTER, 6, offsetof(struct UplinkConfig, uplinkBWP_ToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_uplinkBWP_ToAddModList_5,
		0,
		{ &asn_OER_memb_uplinkBWP_ToAddModList_constr_5, &asn_PER_memb_uplinkBWP_ToAddModList_constr_5,  memb_uplinkBWP_ToAddModList_constraint_1 },
		0, 0, /* No default value */
		"uplinkBWP-ToAddModList"
		},
	{ ATF_POINTER, 5, offsetof(struct UplinkConfig, firstActiveUplinkBWP_Id),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BWP_Id,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"firstActiveUplinkBWP-Id"
		},
	{ ATF_POINTER, 4, offsetof(struct UplinkConfig, pusch_ServingCellConfig),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P49,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ServingCellConfig"
		},
	{ ATF_POINTER, 3, offsetof(struct UplinkConfig, carrierSwitching),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_1084P50,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierSwitching"
		},
	{ ATF_POINTER, 2, offsetof(struct UplinkConfig, powerBoostPi2BPSK),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"powerBoostPi2BPSK"
		},
	{ ATF_POINTER, 1, offsetof(struct UplinkConfig, uplinkChannelBW_PerSCS_List),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_uplinkChannelBW_PerSCS_List_12,
		0,
		{ &asn_OER_memb_uplinkChannelBW_PerSCS_List_constr_12, &asn_PER_memb_uplinkChannelBW_PerSCS_List_constr_12,  memb_uplinkChannelBW_PerSCS_List_constraint_1 },
		0, 0, /* No default value */
		"uplinkChannelBW-PerSCS-List"
		},
};
static const int asn_MAP_UplinkConfig_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_UplinkConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UplinkConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialUplinkBWP */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uplinkBWP-ToReleaseList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uplinkBWP-ToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* firstActiveUplinkBWP-Id */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pusch-ServingCellConfig */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* carrierSwitching */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* powerBoostPi2BPSK */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* uplinkChannelBW-PerSCS-List */
};
asn_SEQUENCE_specifics_t asn_SPC_UplinkConfig_specs_1 = {
	sizeof(struct UplinkConfig),
	offsetof(struct UplinkConfig, _asn_ctx),
	asn_MAP_UplinkConfig_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_UplinkConfig_oms_1,	/* Optional members */
	6, 2,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UplinkConfig = {
	"UplinkConfig",
	"UplinkConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_UplinkConfig_tags_1,
	sizeof(asn_DEF_UplinkConfig_tags_1)
		/sizeof(asn_DEF_UplinkConfig_tags_1[0]), /* 1 */
	asn_DEF_UplinkConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_UplinkConfig_tags_1)
		/sizeof(asn_DEF_UplinkConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UplinkConfig_1,
	8,	/* Elements count */
	&asn_SPC_UplinkConfig_specs_1	/* Additional specs */
};

