/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_MeasTiming_H_
#define	_MeasTiming_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include "ARFCN-ValueNR.h"
#include "SubcarrierSpacing.h"
#include "SSB-MTC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SSB_ToMeasure;
struct SS_RSSI_Measurement;

/* MeasTiming */
typedef struct MeasTiming {
	struct MeasTiming__frequencyAndTiming {
		ARFCN_ValueNR_t	 carrierFreq;
		SubcarrierSpacing_t	 ssbSubcarrierSpacing;
		SSB_MTC_t	 ssb_MeasurementTimingConfiguration;
		struct SS_RSSI_Measurement	*ss_RSSI_Measurement	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *frequencyAndTiming;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SSB_ToMeasure	*ssb_ToMeasure	/* OPTIONAL */;
	PhysCellId_t	*physCellId	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasTiming_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasTiming;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasTiming_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasTiming_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasTiming_H_ */
#include <asn_internal.h>
