/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#include "MeasAndMobParametersCommon.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_supportedGapPattern_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 22)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ssb_RLM_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ssb_RLM_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ssb_AndCSI_RS_RLM_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ssb_AndCSI_RS_RLM_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eventB_MeasAndReport_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eventB_MeasAndReport_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_handoverFDD_TDD_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_handoverFDD_TDD_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eutra_CGI_Reporting_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eutra_CGI_Reporting_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_nr_CGI_Reporting_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_nr_CGI_Reporting_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_independentGapConfig_constr_16 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_independentGapConfig_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_periodicEUTRA_MeasAndReport_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_periodicEUTRA_MeasAndReport_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_handoverFR1_FR2_constr_20 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_handoverFR1_FR2_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_maxNumberCSI_RS_RRM_RS_SINR_constr_22 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_maxNumberCSI_RS_RRM_RS_SINR_constr_22 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_nr_CGI_Reporting_ENDC_constr_29 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_nr_CGI_Reporting_ENDC_constr_29 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eutra_CGI_Reporting_NEDC_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eutra_CGI_Reporting_NEDC_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eutra_CGI_Reporting_NRDC_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eutra_CGI_Reporting_NRDC_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_nr_CGI_Reporting_NEDC_constr_35 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_nr_CGI_Reporting_NEDC_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_nr_CGI_Reporting_NRDC_constr_37 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_nr_CGI_Reporting_NRDC_constr_37 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_supportedGapPattern_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	22	/* (SIZE(22..22)) */};
static asn_per_constraints_t asn_PER_memb_supportedGapPattern_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  22,  22 }	/* (SIZE(22..22)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ssb_RLM_value2enum_3[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ssb_RLM_enum2value_3[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ssb_RLM_specs_3 = {
	asn_MAP_ssb_RLM_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_ssb_RLM_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ssb_RLM_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ssb_RLM_3 = {
	"ssb-RLM",
	"ssb-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_ssb_RLM_tags_3,
	sizeof(asn_DEF_ssb_RLM_tags_3)
		/sizeof(asn_DEF_ssb_RLM_tags_3[0]) - 1, /* 1 */
	asn_DEF_ssb_RLM_tags_3,	/* Same as above */
	sizeof(asn_DEF_ssb_RLM_tags_3)
		/sizeof(asn_DEF_ssb_RLM_tags_3[0]), /* 2 */
	{ &asn_OER_type_ssb_RLM_constr_3, &asn_PER_type_ssb_RLM_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ssb_RLM_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ssb_AndCSI_RS_RLM_value2enum_5[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ssb_AndCSI_RS_RLM_enum2value_5[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ssb_AndCSI_RS_RLM_specs_5 = {
	asn_MAP_ssb_AndCSI_RS_RLM_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_ssb_AndCSI_RS_RLM_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ssb_AndCSI_RS_RLM_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ssb_AndCSI_RS_RLM_5 = {
	"ssb-AndCSI-RS-RLM",
	"ssb-AndCSI-RS-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_ssb_AndCSI_RS_RLM_tags_5,
	sizeof(asn_DEF_ssb_AndCSI_RS_RLM_tags_5)
		/sizeof(asn_DEF_ssb_AndCSI_RS_RLM_tags_5[0]) - 1, /* 1 */
	asn_DEF_ssb_AndCSI_RS_RLM_tags_5,	/* Same as above */
	sizeof(asn_DEF_ssb_AndCSI_RS_RLM_tags_5)
		/sizeof(asn_DEF_ssb_AndCSI_RS_RLM_tags_5[0]), /* 2 */
	{ &asn_OER_type_ssb_AndCSI_RS_RLM_constr_5, &asn_PER_type_ssb_AndCSI_RS_RLM_constr_5, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ssb_AndCSI_RS_RLM_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eventB_MeasAndReport_value2enum_8[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_eventB_MeasAndReport_enum2value_8[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_eventB_MeasAndReport_specs_8 = {
	asn_MAP_eventB_MeasAndReport_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_eventB_MeasAndReport_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eventB_MeasAndReport_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventB_MeasAndReport_8 = {
	"eventB-MeasAndReport",
	"eventB-MeasAndReport",
	&asn_OP_NativeEnumerated,
	asn_DEF_eventB_MeasAndReport_tags_8,
	sizeof(asn_DEF_eventB_MeasAndReport_tags_8)
		/sizeof(asn_DEF_eventB_MeasAndReport_tags_8[0]) - 1, /* 1 */
	asn_DEF_eventB_MeasAndReport_tags_8,	/* Same as above */
	sizeof(asn_DEF_eventB_MeasAndReport_tags_8)
		/sizeof(asn_DEF_eventB_MeasAndReport_tags_8[0]), /* 2 */
	{ &asn_OER_type_eventB_MeasAndReport_constr_8, &asn_PER_type_eventB_MeasAndReport_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eventB_MeasAndReport_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_handoverFDD_TDD_value2enum_10[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_handoverFDD_TDD_enum2value_10[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_handoverFDD_TDD_specs_10 = {
	asn_MAP_handoverFDD_TDD_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverFDD_TDD_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_handoverFDD_TDD_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverFDD_TDD_10 = {
	"handoverFDD-TDD",
	"handoverFDD-TDD",
	&asn_OP_NativeEnumerated,
	asn_DEF_handoverFDD_TDD_tags_10,
	sizeof(asn_DEF_handoverFDD_TDD_tags_10)
		/sizeof(asn_DEF_handoverFDD_TDD_tags_10[0]) - 1, /* 1 */
	asn_DEF_handoverFDD_TDD_tags_10,	/* Same as above */
	sizeof(asn_DEF_handoverFDD_TDD_tags_10)
		/sizeof(asn_DEF_handoverFDD_TDD_tags_10[0]), /* 2 */
	{ &asn_OER_type_handoverFDD_TDD_constr_10, &asn_PER_type_handoverFDD_TDD_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverFDD_TDD_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eutra_CGI_Reporting_value2enum_12[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_eutra_CGI_Reporting_enum2value_12[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_eutra_CGI_Reporting_specs_12 = {
	asn_MAP_eutra_CGI_Reporting_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_eutra_CGI_Reporting_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eutra_CGI_Reporting_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eutra_CGI_Reporting_12 = {
	"eutra-CGI-Reporting",
	"eutra-CGI-Reporting",
	&asn_OP_NativeEnumerated,
	asn_DEF_eutra_CGI_Reporting_tags_12,
	sizeof(asn_DEF_eutra_CGI_Reporting_tags_12)
		/sizeof(asn_DEF_eutra_CGI_Reporting_tags_12[0]) - 1, /* 1 */
	asn_DEF_eutra_CGI_Reporting_tags_12,	/* Same as above */
	sizeof(asn_DEF_eutra_CGI_Reporting_tags_12)
		/sizeof(asn_DEF_eutra_CGI_Reporting_tags_12[0]), /* 2 */
	{ &asn_OER_type_eutra_CGI_Reporting_constr_12, &asn_PER_type_eutra_CGI_Reporting_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eutra_CGI_Reporting_specs_12	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nr_CGI_Reporting_value2enum_14[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_CGI_Reporting_enum2value_14[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_CGI_Reporting_specs_14 = {
	asn_MAP_nr_CGI_Reporting_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_CGI_Reporting_enum2value_14,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_CGI_Reporting_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_CGI_Reporting_14 = {
	"nr-CGI-Reporting",
	"nr-CGI-Reporting",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_CGI_Reporting_tags_14,
	sizeof(asn_DEF_nr_CGI_Reporting_tags_14)
		/sizeof(asn_DEF_nr_CGI_Reporting_tags_14[0]) - 1, /* 1 */
	asn_DEF_nr_CGI_Reporting_tags_14,	/* Same as above */
	sizeof(asn_DEF_nr_CGI_Reporting_tags_14)
		/sizeof(asn_DEF_nr_CGI_Reporting_tags_14[0]), /* 2 */
	{ &asn_OER_type_nr_CGI_Reporting_constr_14, &asn_PER_type_nr_CGI_Reporting_constr_14, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_CGI_Reporting_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_independentGapConfig_value2enum_16[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_independentGapConfig_enum2value_16[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_independentGapConfig_specs_16 = {
	asn_MAP_independentGapConfig_value2enum_16,	/* "tag" => N; sorted by tag */
	asn_MAP_independentGapConfig_enum2value_16,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_independentGapConfig_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_independentGapConfig_16 = {
	"independentGapConfig",
	"independentGapConfig",
	&asn_OP_NativeEnumerated,
	asn_DEF_independentGapConfig_tags_16,
	sizeof(asn_DEF_independentGapConfig_tags_16)
		/sizeof(asn_DEF_independentGapConfig_tags_16[0]) - 1, /* 1 */
	asn_DEF_independentGapConfig_tags_16,	/* Same as above */
	sizeof(asn_DEF_independentGapConfig_tags_16)
		/sizeof(asn_DEF_independentGapConfig_tags_16[0]), /* 2 */
	{ &asn_OER_type_independentGapConfig_constr_16, &asn_PER_type_independentGapConfig_constr_16, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_independentGapConfig_specs_16	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_periodicEUTRA_MeasAndReport_value2enum_18[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_periodicEUTRA_MeasAndReport_enum2value_18[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_periodicEUTRA_MeasAndReport_specs_18 = {
	asn_MAP_periodicEUTRA_MeasAndReport_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_periodicEUTRA_MeasAndReport_enum2value_18,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_periodicEUTRA_MeasAndReport_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_periodicEUTRA_MeasAndReport_18 = {
	"periodicEUTRA-MeasAndReport",
	"periodicEUTRA-MeasAndReport",
	&asn_OP_NativeEnumerated,
	asn_DEF_periodicEUTRA_MeasAndReport_tags_18,
	sizeof(asn_DEF_periodicEUTRA_MeasAndReport_tags_18)
		/sizeof(asn_DEF_periodicEUTRA_MeasAndReport_tags_18[0]) - 1, /* 1 */
	asn_DEF_periodicEUTRA_MeasAndReport_tags_18,	/* Same as above */
	sizeof(asn_DEF_periodicEUTRA_MeasAndReport_tags_18)
		/sizeof(asn_DEF_periodicEUTRA_MeasAndReport_tags_18[0]), /* 2 */
	{ &asn_OER_type_periodicEUTRA_MeasAndReport_constr_18, &asn_PER_type_periodicEUTRA_MeasAndReport_constr_18, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_periodicEUTRA_MeasAndReport_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_handoverFR1_FR2_value2enum_20[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_handoverFR1_FR2_enum2value_20[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_handoverFR1_FR2_specs_20 = {
	asn_MAP_handoverFR1_FR2_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverFR1_FR2_enum2value_20,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_handoverFR1_FR2_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverFR1_FR2_20 = {
	"handoverFR1-FR2",
	"handoverFR1-FR2",
	&asn_OP_NativeEnumerated,
	asn_DEF_handoverFR1_FR2_tags_20,
	sizeof(asn_DEF_handoverFR1_FR2_tags_20)
		/sizeof(asn_DEF_handoverFR1_FR2_tags_20[0]) - 1, /* 1 */
	asn_DEF_handoverFR1_FR2_tags_20,	/* Same as above */
	sizeof(asn_DEF_handoverFR1_FR2_tags_20)
		/sizeof(asn_DEF_handoverFR1_FR2_tags_20[0]), /* 2 */
	{ &asn_OER_type_handoverFR1_FR2_constr_20, &asn_PER_type_handoverFR1_FR2_constr_20, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverFR1_FR2_specs_20	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumberCSI_RS_RRM_RS_SINR_value2enum_22[] = {
	{ 0,	2,	"n4" },
	{ 1,	2,	"n8" },
	{ 2,	3,	"n16" },
	{ 3,	3,	"n32" },
	{ 4,	3,	"n64" },
	{ 5,	3,	"n96" }
};
static const unsigned int asn_MAP_maxNumberCSI_RS_RRM_RS_SINR_enum2value_22[] = {
	2,	/* n16(2) */
	3,	/* n32(3) */
	0,	/* n4(0) */
	4,	/* n64(4) */
	1,	/* n8(1) */
	5	/* n96(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumberCSI_RS_RRM_RS_SINR_specs_22 = {
	asn_MAP_maxNumberCSI_RS_RRM_RS_SINR_value2enum_22,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumberCSI_RS_RRM_RS_SINR_enum2value_22,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_22 = {
	"maxNumberCSI-RS-RRM-RS-SINR",
	"maxNumberCSI-RS-RRM-RS-SINR",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22,
	sizeof(asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22)
		/sizeof(asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22[0]) - 1, /* 1 */
	asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22,	/* Same as above */
	sizeof(asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22)
		/sizeof(asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_tags_22[0]), /* 2 */
	{ &asn_OER_type_maxNumberCSI_RS_RRM_RS_SINR_constr_22, &asn_PER_type_maxNumberCSI_RS_RRM_RS_SINR_constr_22, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumberCSI_RS_RRM_RS_SINR_specs_22	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nr_CGI_Reporting_ENDC_value2enum_29[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_CGI_Reporting_ENDC_enum2value_29[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_CGI_Reporting_ENDC_specs_29 = {
	asn_MAP_nr_CGI_Reporting_ENDC_value2enum_29,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_CGI_Reporting_ENDC_enum2value_29,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_CGI_Reporting_ENDC_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_CGI_Reporting_ENDC_29 = {
	"nr-CGI-Reporting-ENDC",
	"nr-CGI-Reporting-ENDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_CGI_Reporting_ENDC_tags_29,
	sizeof(asn_DEF_nr_CGI_Reporting_ENDC_tags_29)
		/sizeof(asn_DEF_nr_CGI_Reporting_ENDC_tags_29[0]) - 1, /* 1 */
	asn_DEF_nr_CGI_Reporting_ENDC_tags_29,	/* Same as above */
	sizeof(asn_DEF_nr_CGI_Reporting_ENDC_tags_29)
		/sizeof(asn_DEF_nr_CGI_Reporting_ENDC_tags_29[0]), /* 2 */
	{ &asn_OER_type_nr_CGI_Reporting_ENDC_constr_29, &asn_PER_type_nr_CGI_Reporting_ENDC_constr_29, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_CGI_Reporting_ENDC_specs_29	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eutra_CGI_Reporting_NEDC_value2enum_31[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_eutra_CGI_Reporting_NEDC_enum2value_31[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_eutra_CGI_Reporting_NEDC_specs_31 = {
	asn_MAP_eutra_CGI_Reporting_NEDC_value2enum_31,	/* "tag" => N; sorted by tag */
	asn_MAP_eutra_CGI_Reporting_NEDC_enum2value_31,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eutra_CGI_Reporting_NEDC_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eutra_CGI_Reporting_NEDC_31 = {
	"eutra-CGI-Reporting-NEDC",
	"eutra-CGI-Reporting-NEDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_eutra_CGI_Reporting_NEDC_tags_31,
	sizeof(asn_DEF_eutra_CGI_Reporting_NEDC_tags_31)
		/sizeof(asn_DEF_eutra_CGI_Reporting_NEDC_tags_31[0]) - 1, /* 1 */
	asn_DEF_eutra_CGI_Reporting_NEDC_tags_31,	/* Same as above */
	sizeof(asn_DEF_eutra_CGI_Reporting_NEDC_tags_31)
		/sizeof(asn_DEF_eutra_CGI_Reporting_NEDC_tags_31[0]), /* 2 */
	{ &asn_OER_type_eutra_CGI_Reporting_NEDC_constr_31, &asn_PER_type_eutra_CGI_Reporting_NEDC_constr_31, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eutra_CGI_Reporting_NEDC_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eutra_CGI_Reporting_NRDC_value2enum_33[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_eutra_CGI_Reporting_NRDC_enum2value_33[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_eutra_CGI_Reporting_NRDC_specs_33 = {
	asn_MAP_eutra_CGI_Reporting_NRDC_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_eutra_CGI_Reporting_NRDC_enum2value_33,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eutra_CGI_Reporting_NRDC_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eutra_CGI_Reporting_NRDC_33 = {
	"eutra-CGI-Reporting-NRDC",
	"eutra-CGI-Reporting-NRDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_eutra_CGI_Reporting_NRDC_tags_33,
	sizeof(asn_DEF_eutra_CGI_Reporting_NRDC_tags_33)
		/sizeof(asn_DEF_eutra_CGI_Reporting_NRDC_tags_33[0]) - 1, /* 1 */
	asn_DEF_eutra_CGI_Reporting_NRDC_tags_33,	/* Same as above */
	sizeof(asn_DEF_eutra_CGI_Reporting_NRDC_tags_33)
		/sizeof(asn_DEF_eutra_CGI_Reporting_NRDC_tags_33[0]), /* 2 */
	{ &asn_OER_type_eutra_CGI_Reporting_NRDC_constr_33, &asn_PER_type_eutra_CGI_Reporting_NRDC_constr_33, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eutra_CGI_Reporting_NRDC_specs_33	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nr_CGI_Reporting_NEDC_value2enum_35[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_CGI_Reporting_NEDC_enum2value_35[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_CGI_Reporting_NEDC_specs_35 = {
	asn_MAP_nr_CGI_Reporting_NEDC_value2enum_35,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_CGI_Reporting_NEDC_enum2value_35,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_CGI_Reporting_NEDC_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_CGI_Reporting_NEDC_35 = {
	"nr-CGI-Reporting-NEDC",
	"nr-CGI-Reporting-NEDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_CGI_Reporting_NEDC_tags_35,
	sizeof(asn_DEF_nr_CGI_Reporting_NEDC_tags_35)
		/sizeof(asn_DEF_nr_CGI_Reporting_NEDC_tags_35[0]) - 1, /* 1 */
	asn_DEF_nr_CGI_Reporting_NEDC_tags_35,	/* Same as above */
	sizeof(asn_DEF_nr_CGI_Reporting_NEDC_tags_35)
		/sizeof(asn_DEF_nr_CGI_Reporting_NEDC_tags_35[0]), /* 2 */
	{ &asn_OER_type_nr_CGI_Reporting_NEDC_constr_35, &asn_PER_type_nr_CGI_Reporting_NEDC_constr_35, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_CGI_Reporting_NEDC_specs_35	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nr_CGI_Reporting_NRDC_value2enum_37[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_CGI_Reporting_NRDC_enum2value_37[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_CGI_Reporting_NRDC_specs_37 = {
	asn_MAP_nr_CGI_Reporting_NRDC_value2enum_37,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_CGI_Reporting_NRDC_enum2value_37,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_CGI_Reporting_NRDC_tags_37[] = {
	(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_CGI_Reporting_NRDC_37 = {
	"nr-CGI-Reporting-NRDC",
	"nr-CGI-Reporting-NRDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_CGI_Reporting_NRDC_tags_37,
	sizeof(asn_DEF_nr_CGI_Reporting_NRDC_tags_37)
		/sizeof(asn_DEF_nr_CGI_Reporting_NRDC_tags_37[0]) - 1, /* 1 */
	asn_DEF_nr_CGI_Reporting_NRDC_tags_37,	/* Same as above */
	sizeof(asn_DEF_nr_CGI_Reporting_NRDC_tags_37)
		/sizeof(asn_DEF_nr_CGI_Reporting_NRDC_tags_37[0]), /* 2 */
	{ &asn_OER_type_nr_CGI_Reporting_NRDC_constr_37, &asn_PER_type_nr_CGI_Reporting_NRDC_constr_37, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_CGI_Reporting_NRDC_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasAndMobParametersCommon_1[] = {
	{ ATF_POINTER, 16, offsetof(struct MeasAndMobParametersCommon, supportedGapPattern),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_supportedGapPattern_constr_2, &asn_PER_memb_supportedGapPattern_constr_2,  memb_supportedGapPattern_constraint_1 },
		0, 0, /* No default value */
		"supportedGapPattern"
		},
	{ ATF_POINTER, 15, offsetof(struct MeasAndMobParametersCommon, ssb_RLM),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ssb_RLM_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-RLM"
		},
	{ ATF_POINTER, 14, offsetof(struct MeasAndMobParametersCommon, ssb_AndCSI_RS_RLM),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ssb_AndCSI_RS_RLM_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-AndCSI-RS-RLM"
		},
	{ ATF_POINTER, 13, offsetof(struct MeasAndMobParametersCommon, eventB_MeasAndReport),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eventB_MeasAndReport_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventB-MeasAndReport"
		},
	{ ATF_POINTER, 12, offsetof(struct MeasAndMobParametersCommon, handoverFDD_TDD),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverFDD_TDD_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverFDD-TDD"
		},
	{ ATF_POINTER, 11, offsetof(struct MeasAndMobParametersCommon, eutra_CGI_Reporting),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eutra_CGI_Reporting_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting"
		},
	{ ATF_POINTER, 10, offsetof(struct MeasAndMobParametersCommon, nr_CGI_Reporting),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_CGI_Reporting_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting"
		},
	{ ATF_POINTER, 9, offsetof(struct MeasAndMobParametersCommon, independentGapConfig),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_independentGapConfig_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"independentGapConfig"
		},
	{ ATF_POINTER, 8, offsetof(struct MeasAndMobParametersCommon, periodicEUTRA_MeasAndReport),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_periodicEUTRA_MeasAndReport_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodicEUTRA-MeasAndReport"
		},
	{ ATF_POINTER, 7, offsetof(struct MeasAndMobParametersCommon, handoverFR1_FR2),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverFR1_FR2_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverFR1-FR2"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasAndMobParametersCommon, maxNumberCSI_RS_RRM_RS_SINR),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumberCSI_RS_RRM_RS_SINR_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberCSI-RS-RRM-RS-SINR"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasAndMobParametersCommon, nr_CGI_Reporting_ENDC),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_CGI_Reporting_ENDC_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-ENDC"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasAndMobParametersCommon, eutra_CGI_Reporting_NEDC),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eutra_CGI_Reporting_NEDC_31,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting-NEDC"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasAndMobParametersCommon, eutra_CGI_Reporting_NRDC),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eutra_CGI_Reporting_NRDC_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting-NRDC"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasAndMobParametersCommon, nr_CGI_Reporting_NEDC),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_CGI_Reporting_NEDC_35,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-NEDC"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasAndMobParametersCommon, nr_CGI_Reporting_NRDC),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_CGI_Reporting_NRDC_37,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-NRDC"
		},
};
static const int asn_MAP_MeasAndMobParametersCommon_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_MeasAndMobParametersCommon_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasAndMobParametersCommon_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedGapPattern */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssb-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ssb-AndCSI-RS-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eventB-MeasAndReport */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* handoverFDD-TDD */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* eutra-CGI-Reporting */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* nr-CGI-Reporting */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* independentGapConfig */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* periodicEUTRA-MeasAndReport */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* handoverFR1-FR2 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* maxNumberCSI-RS-RRM-RS-SINR */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* nr-CGI-Reporting-ENDC */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* eutra-CGI-Reporting-NEDC */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* eutra-CGI-Reporting-NRDC */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* nr-CGI-Reporting-NEDC */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* nr-CGI-Reporting-NRDC */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasAndMobParametersCommon_specs_1 = {
	sizeof(struct MeasAndMobParametersCommon),
	offsetof(struct MeasAndMobParametersCommon, _asn_ctx),
	asn_MAP_MeasAndMobParametersCommon_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_MeasAndMobParametersCommon_oms_1,	/* Optional members */
	3, 13,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasAndMobParametersCommon = {
	"MeasAndMobParametersCommon",
	"MeasAndMobParametersCommon",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasAndMobParametersCommon_tags_1,
	sizeof(asn_DEF_MeasAndMobParametersCommon_tags_1)
		/sizeof(asn_DEF_MeasAndMobParametersCommon_tags_1[0]), /* 1 */
	asn_DEF_MeasAndMobParametersCommon_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasAndMobParametersCommon_tags_1)
		/sizeof(asn_DEF_MeasAndMobParametersCommon_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasAndMobParametersCommon_1,
	16,	/* Elements count */
	&asn_SPC_MeasAndMobParametersCommon_specs_1	/* Additional specs */
};

