/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-15.asn"
 * 	`asn1c -fcompound-names -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UE_NR_Capability_v15g0_H_
#define	_UE_NR_Capability_v15g0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RF_Parameters_v15g0;
struct UE_NR_Capability_v15j0;

/* UE-NR-Capability-v15g0 */
typedef struct UE_NR_Capability_v15g0 {
	struct RF_Parameters_v15g0	*rf_Parameters_v15g0	/* OPTIONAL */;
	struct UE_NR_Capability_v15j0	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_NR_Capability_v15g0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_NR_Capability_v15g0;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_NR_Capability_v15g0_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_NR_Capability_v15g0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_NR_Capability_v15g0_H_ */
#include <asn_internal.h>
